### ISSUE TITLE
WAS Survey: Remove the Other (not assigned) waypoint.

### ISSUE THREAD

**Issue by pjdohertygis** [pjdohertygis/WideAreaSearchTemplates#100]
"I don’t think we need an Other (not assigned) AND Other Hazard. If I had to choose, I would axe Other (not assigned) since that was never one of the original 24." Collin Grove - OH-TF1

**Comment by pjdohertygis** [comment]
The initial intent was to give users and opportunity to add a "wildcard" that was not assigned to to 21-24. However, I think this is confusing and still requires guidance. Paul votes to also discard this waypoint.

**Comment by pjdohertygis** [comment]
I'm ok with getting rid of the Other (I don't think it is used very often) "Katie Breland"

**Comment by t-mahon** [comment]
I'm okay with getting rid of Other (not assigned).

At the moment FDNY-SOCTF has this assigned for storm events, but we can certainly adopt another variable.  In fact the 'Searched' waypoint will likely be a good replacement, and we still have the other 4 variables.  

Just for reference I'm attaching the SOCTF/Parks Interoperability document for how we use the waypoints from the WAS survey and then share a view to the Parks Dept.
[SOCTF and Parks Chainsaw Interoperability 20201216.pdf](https://github.com/pjdohertygis/WideAreaSearchTemplates/files/5815388/SOCTF.and.Parks.Chainsaw.Interoperability.20201216.pdf)

**Comment by pjdohertygis** [comment]
Removed.
