### ISSUE TITLE
Survey123 App Enhancement: Dealing with keyboards

### ISSUE THREAD

**Issue by pjdohertygis** [pjdohertygis/WideAreaSearchTemplates#101]
"Is there a way to eliminate the text search ability in the Waypoint dropdown? It’s annoying that the screen real estate is cut in half even after you select your waypoint. I know it sounds silly, but the OH guys were counting the taps to collect a point this season and that was an issue they brought up." 

"Can we make a dropdown/disclosure triangle for Comments? I noticed a lot this season that when you scroll with your finger starting in that field, the keyboard comes up, and you have to scroll way up and then back down to make the keyboard disappear to get to the photo icon at the bottom." - Collin Grove

**Comment by pjdohertygis** [comment]
@IsmaelInRedlands we hear a lot of feedback that keyboards are cumbersome in Survey123.

iOS: many people don't know that you can slide the keyboard close in iOS.
Android: has a little tab at the bottom left of the interface to close the keyboard. 

Is this purely a training issue or something that Survey123 can change in the UI?

**Comment by IsmaelInRedlands** [comment]
Lets get on a conference call to record the pain points.

**Comment by pjdohertygis** [comment]
Sounds good - I'll reach out to set that up @IsmaelInRedlands later today or tomorrow.

Here is a screenshot  ![image](https://user-images.githubusercontent.com/4256979/102396537-70310280-3f91-11eb-8741-c6a0b2d59ac7.png)- I've filled out the Comments field on my iPhone, but now want to finish the form and then eventually check the submit button. But the keyboard is open and in the way. On an iPhone I need to swipe the keyboard down to proceed and most firefighters won't know this. I think on Android there is a little vague tab or button which is only marginally better.

Sometimes the green check / submit button shows up and I've seen users click on that, expecting it to complete the question and close the keyboard.

So while I know we cannot change the default iOS or Android keyboard behavior....could Survey123 trigger the keyboard to close when I tap on the next question or try to scroll the page?

**Comment by IsmaelInRedlands** [comment]
Recorded this based on our conversation this morning: https://www.youtube.com/watch?v=e9tg127vdDY
Lets reconnect in late January to close the loop on this.

**Comment by pjdohertygis** [comment]
Yes I think that covers the keyboard issue pretty well! @jdokemaps is this similar to what you experience with Android?

**Comment by jdokemaps** [comment]
@pjdohertygis yes. that is the same behavior that I see in Android.

**Comment by pjdohertygis** [comment]
Ok we added guidance in the training video, but still hoping the @IsmaelInRedlands Survey123 Team can help address this in the UI. 

Also noticed on iPad keyboards, there was a close keyboard button.

**Comment by pjdohertygis** [comment]
Another user getting tripped up by the keyboard not closing 

![image](https://user-images.githubusercontent.com/4256979/115263513-7ed82380-a103-11eb-9696-f958f8b4f1e5.png)

**Comment by pjdohertygis** [comment]
@IsmaelInRedlands we are still hitting issues with keyboards in Survey123... any updates on this? 


When they are doing typing in a comment, they click on the checkmark because they *think* this will close the keyboard. But that checkmark is to submit a survey. Then there is no obvious way to close the keyboard other than swiping (or on Android there is a tiny carat to close the keyboard)

![image](https://user-images.githubusercontent.com/4256979/142669234-dbd3fe35-c15e-41b4-888f-af2c5cc92171.png)

**Comment by IsmaelInRedlands** [comment]
@pjdohertygis  I do not think we can fix this as the keyboard is provided by the operating system. Let me ask around and see if I find a more creative mind to come up with a solution.
