### ISSUE TITLE
Change Assignment Template name to "Segments"

### ISSUE THREAD

**Issue by pjdohertygis** [pjdohertygis/WideAreaSearchTemplates#105]
Segments are assigned to teams and can be repeated. Segments are the actual geography that is drawn, then people & resources are assigned to them. Segments are also the term used in most trainings. 

Anyone opposed?

I've temporarily made edits to the name here https://napsg.maps.arcgis.com/home/item.html?id=b6ad58297c524e049af1df5a137dc49c

**Comment by grover556** [comment]
Should we work "Division" into the name to stay consistent with ICS terminology? Even if the IST calls the geographic areas assigned to task forces Divisions too, it's on a different layer.

Division Status? Team Div Status? Team Divisions? TF Divisions?

**Comment by pjdohertygis** [comment]
@grover556 we actually worked Divisions into this template here https://napsg.maps.arcgis.com/home/item.html?id=f74fb2be98a641299bac95984f1f9464

So as of right now the hierarchy would be 

**Operational Areas**
These are each a drop down here https://napsg.maps.arcgis.com/home/item.html?id=f74fb2be98a641299bac95984f1f9464
Incident Area = the entire potential impact area - drawn by the AHJ and/or FEMA GIS, based on the hazard modelled.
Branches = large areas of jurisdiction (e.g., States or multiple counties as per AHJ). 
Divisions = geographic areas assigned to Task Forces (e.g., Counties, Large Islands, etc). 

**Segments**
Then in it's own layer are search segments, formerly known as assignments. https://napsg.maps.arcgis.com/home/item.html?id=b6ad58297c524e049af1df5a137dc49c
Segments = are geographic areas assigned for search to be completed in a known time period. These should be drawn by the Task Forces to ensure their "Division" is covered.

This adapts what is already taught in ICS / Wildland Fire to wide area search operations.

Is there any guidance in any of the US&R training specific to this topic we can adopt?

**Comment by pjdohertygis** [comment]
Here is more terminology from NWCG 

![image](https://user-images.githubusercontent.com/4256979/102540696-6684c900-407d-11eb-8c28-30c5c6fe2f0f.png)
![image](https://user-images.githubusercontent.com/4256979/102540764-81573d80-407d-11eb-97a1-5f7723c612f3.png)
https://www.nwcg.gov/about-the-nwcg-glossary-of-wildland-fire

In wildland fire, assignments (204s) are not made on segments, because they are not doing wide area search. But in WAS we need a way to designate where the assignment is?

**Comment by pjdohertygis** [comment]
Implemented
