### ISSUE TITLE
WAS Form: Create an "original waypoint" field.

### ISSUE THREAD

**Issue by pjdohertygis** [pjdohertygis/WideAreaSearchTemplates#106]
One of the topics that has come up if we use the "single waypoint" method is the loss of data (i.e., the original waypoint).

![image](https://user-images.githubusercontent.com/4256979/102557064-54fcea80-4098-11eb-83e4-23d9d8611e40.png)

Example: Squad 1 enters a new waypoint for "Victims/Survivors Confirmed", needs follow-up, Squad 2 follows-up and enters "Rescue", completed. 

In Survey123 and QuickCapture we should keep a record of the "original waypoint". 

With Survey123 this can be done with a calculation (thanks to Colleen!) writing to a field.
With QuickCapture this must be "hard-coded". 

This is related to, but not identical to: https://github.com/pjdohertygis/WideAreaSearchTemplates/issues/40

**Comment by CLivingstone** [comment]
In S123, a record of the original waypoint can be accomplished with a field with the calculation **once(${waypoint})**.  The once() function prevents a field from being recalculated with changes to the waypoint.

**Comment by pjdohertygis** [comment]
Thank you @CLivingstone that is an elegant solution!
