### ISSUE TITLE
QuickCapture: Weak Connection Troubleshooting

### ISSUE THREAD

**Issue by pjdohertygis** [pjdohertygis/WideAreaSearchTemplates#107]
We keep getting errors related to either 

1) WiFi - a user forgets to turn off WiFi on their device and we get some bounce in the track.
2) Location permission settings - if a user does not setup location permissions correctly, it will draw a straight line connecting the location where they start their track, to the next location where they open the app again. 
3) 1X Connection Lock-out - Even when the user signed into QuickCapture before leaving their home / base, when they get into a 1X / weak cell connection, it tells them they cannot access the app. It seems to work OK in airplane mode, but this weak connection causes a big issue. {the QuickCapture is working on this, resolved in Survey123 as per Survey123 Bug: Weak wifi connection forcing a login}. 

Can someone help me write a troubleshooting slide / one-pager for QuickCapture? 

@IsmaelInRedlands have any other users created any troubleshooting guides? 

![image](https://user-images.githubusercontent.com/4256979/102815644-aeb42c00-439a-11eb-84d5-d6e588c0e396.png)

**Comment by IsmaelInRedlands** [comment]
We are still working on this. There are multiple factors producing this type of issue, including the usual Location Settings in the app but also the exact device people use (particularly in Android). At this point in time, I think it is best for you not to send further instructions to users to avoid confusion.  We should be able to make progress with this in the first half of 2021 to a point where people should not need to worry about app settings.

**Comment by pjdohertygis** [comment]
ok sounds good - we will keep this issue open and post any "clues" we find. @jdokemaps is testing QuickCapture and Field Maps with tracking simultaneously (while kayaking) on his Android this week. He hit some issues with both apps and wondering if his phone is having trouble running both apps simultaneously (which we are not planning on doing in real life, we just wanted to compare the tracks) or if it is something else. He will try to isolate this tomorrow.

**Comment by IsmaelInRedlands** [comment]
In principle, running both apps simultaneously should not be an issue.

**Comment by pjdohertygis** [comment]
@jdokemaps running Pixel4XL and Android 11.0 is hitting issues when using QuickCapture and FieldMaps tracking together. Also, he is confident his location permission settings changed themselves for QuickCapture.

**Comment by pjdohertygis** [comment]
I believe v1.9 addressed these issues, we will re-open if it comes back up. https://doc.arcgis.com/en/quickcapture/faq/whatsnew.htm

**Comment by pjdohertygis** [comment]
@IsmaelInRedlands indeed you are correct. This weekend I hit an issue, steps below.

1) While in Redlands I've been doing extensive testing with QuickCapture with no issue, both online and offline (via AirPlane mode)
2) I never sign out QuickCapture 
3) We drive up to the San Gabriel's, get to our campground with a 1 bar (No LTE) connection, go to QuickCapture and get promoted to login. 
4) Attempt to login and it says I cannot do this offline, even though I was previously signed in.
5) I go to continue without signing in and the projects I already have on my device do not appear. 

At this point a firefighter on a Hurricane or earthquake would be dead in the water with no way to record data.

6) The next morning we hiked up to the ridge and peak. At some point I get a weak LTE connection and now I can sign-in and use QuickCapture for the rest of the hike.

![image](https://user-images.githubusercontent.com/4256979/114405444-b2033b80-9b74-11eb-885a-e11e21243a4b.png)

![image](https://user-images.githubusercontent.com/4256979/114405489-ba5b7680-9b74-11eb-9ff6-efc1ed25d21b.png)

*Note Survey123 also signed me out but at least allowed me to access my existing forms.

**Comment by IsmaelInRedlands** [comment]
This happened to me as well this weekend. Please log as a Tech Support incident. One should not be logged out, under any circumstances.

**Comment by pjdohertygis** [comment]
Logged #02782764: QuickCapture authentication issues in weak connection areas.

**Comment by pjdohertygis** [comment]
Addressed with v1.11 - we still recommend airplane mode if working in comms limited environment.
