### ISSUE TITLE
WAS Form: Find a way to account for pets & companion animals rescued to the Survey

### ISSUE THREAD

**Issue by pjdohertygis** [pjdohertygis/WideAreaSearchTemplates#11]
See Kevin Henson's Notes and request from SC SEOC / SC Governor

**Comment by pjdohertygis** [comment]
**Options**
A: Add a specific pet rescue waypoint
B: Use it as a follow-up question on rescue (count) - issue: this might skew the rescue waypoint data.
C: Do nothing.

**Comment by epratt5** [comment]
I think Option C. As far as indicating the type of animal, I would say have a basic multiple choice question: Dog, Cat, Bird, Other

**Comment by dweber-mo** [comment]
I agree that option C would be best.  It seems like the comment field could suffice for mission specific need for more detail.

**Comment by jdokemaps** [comment]
We decided to give option C a try. When you select Animal Issue as the waypoint, it will add an Animal Count field where you can enter the number of animals and an Animal Issue Comments field where you can comment on the type of animal, if the animal is aggressive, if it needs to be rescued, etc.

**Comment by pjdohertygis** [comment]
From Collin Grove - OH-TF1 "I feel the same with Animal Evacuation, where it should be in the category previously known as Animal Issue." 

The main reason we added this waypoint is 1) the ability to quickly summarize animal rescues 2) to clearly differentiate a hazard from an accomplishment / kudos

**Comment by dweber-mo** [comment]
Paul,
This has been an ask for reporting by the IST many times on deployments.  Although, I don’t like adding waypoints unnecessarily, this one is needed as much as abandoned vehicles for floods…

Dave Weber, PE, SE
Phone 573.875.8799
Cell 573.999.5545

**Comment by grover556** [comment]
I wasn't aware of the length of time this issue was open. Should rescue -or- other problem just be a branch question within the animal issue icon?

**Comment by dweber-mo** [comment]
I think it could be as long as this is something that could easily be reported/tracked/tallied by the IST.

Dave Weber, PE, SE
Phone 573.875.8799
Cell 573.999.5545

**Comment by pjdohertygis** [comment]
I feel that a rescue/evac for an animal is an action taken that is very different than identifying a hazard. Therefore using one symbol to reflect both is problematic. 

Even the symbology should be different - according to https://www.napsgfoundation.org/wp-content/uploads/2020/03/NAPSG-Foundation-Incident-Symbol-Guideline_v4.0_03212020.pdf

Diamonds = Hazards = Animal Issue
Circles = Incident symbols = Animal Evacuation
{Side note: In 2022, I'd like to work a revamp of the symbology, only hazards should be diamonds whereas I am guessing with Garmin we could only do diamonds)

**Comment by pjdohertygis** [comment]
"An “Animal Issue” is normally used when you can’t complete a task BECAUSE of an animal OR the animal is in a life threatening situation and needs to be rescued.  The “Animal Evac” or maybe we should call it “PET EVAC” so it won’t confuse people just keeps track of how many pets have been removed." - Katie Breland TX-TF1

**Comment by pjdohertygis** [comment]
After much debate - I think the consensus is accept this as a new unique waypoint because 1) it is become increasingly more common of a request 2) it is unique and not easily covered by existing waypoints (the existing animal issue waypoint is a hazard and significantly different from an animal evacuation, combining the two would make summary statistics very challenging and confusing when looking at maps) 3) it has unique secondary questions / categories

**Comment by pjdohertygis** [comment]
Implemented a pet evacuation waypoint.
