### ISSUE TITLE
New basemap called OSM Daylight 

### ISSUE THREAD

**Issue by jwarzi** [pjdohertygis/WideAreaSearchTemplates#114]
Is the new basemap called OSM Daylight amponly available for use when you make offline maps?  I don't see it as an online basemap when I am in a survey and click on the  map gallery picker.  Would be nice to have the same map available online and offline.

**Comment by pjdohertygis** [comment]
Affirmative. You can find a few different themes for it in ArcGIS Online https://www.esri.com/arcgis-blog/products/arcgis-living-atlas/mapping/dawn-of-osm-daylight-in-arcgis/

But you need to search for it and then add as a basemap
![image](https://user-images.githubusercontent.com/4256979/109316971-27f85100-781a-11eb-8b14-cee664c1ce8a.png)

I've tested online and offline around California and it works really well.

Which theme do you think works best for US&R? 

Also Collin G was working on using the vector tile capability to make our own US&R Theme using the Daylight basemap foundation.
