### ISSUE TITLE
Survey123 v8 - Pet Evac 

### ISSUE THREAD

**Issue by jwarzi** [pjdohertygis/WideAreaSearchTemplates#115]
Is this waypoint name aligned with FEMA USARs names/terms?  We usually refer to these sorts of rescues as companion animals or household pets and/or companion animals

**Comment by pjdohertygis** [comment]
@jwarzi - good question, my understanding is Katie B and Jeff Saunders looked into this via the PETS Act https://www.avma.org/pets-act-faq and confirmed with A-SAR.

I think also the attention was to differentiate between livestock.   

Let's make sure we address properly in the data dictionary, but I think "Pet" is OK.
