### ISSUE TITLE
Symbology for Survivor Detected

### ISSUE THREAD

**Issue by jwarzi** [pjdohertygis/WideAreaSearchTemplates#116]
With v8 and the name changes of the icon, do we update the icons too?  For example, should "Survivor Detected" now be an S instead of V?

![20210124_153425](https://user-images.githubusercontent.com/19979978/105644359-d182a600-5e5a-11eb-88ff-dbba23c721bc.jpg)

**Comment by pjdohertygis** [comment]
I agree @jwarzi. I am hoping we can do a Symbology overhaul for 2022 by working with the FEMA US&R Search Group.

Diamonds = hazards, so most of these should be circles for operational intelligence as per public safety symbology. 
Victim = deceased, and Survivor = alive so V's should be S's.

**Comment by pjdohertygis** [comment]
The group consensus is.... don't change the symbols or the terminology.
