### ISSUE TITLE
Survey123 Crash with Daylight Basemap

### ISSUE THREAD

**Issue by pjdohertygis** [pjdohertygis/WideAreaSearchTemplates#119]
This was reported as an Android bug, but may be a wider issue. 

RE: Esri Case #02754672 - Zooming in on geopoint map crashes the Survey123 app on certain devices.

**Comment by pjdohertygis** [comment]
v3.13 or 3.14 may provide a fix for this, it appears to be a RAM/memory issue.

**Comment by jdokemaps** [comment]
In Product Plan

![image](https://user-images.githubusercontent.com/52461518/130109895-efd176fd-be73-451f-aa14-62a82fb8bad4.png)

**Comment by pjdohertygis** [comment]
Fixed
