### ISSUE TITLE
QuickCapture Multiple Project User Input 

### ISSUE THREAD

**Issue by pjdohertygis** [pjdohertygis/WideAreaSearchTemplates#127]
Esri is working on this but wanted to document the "issue" so we can track it here. 

We are currently using the Team Name for Project User Input, but the teams would also like to indicate their squad number to better identify where each squad has been and filter in Dashboards. To do this we need Esri to implement the ability to have multiple project user inputs.

@IsmaelInRedlands any update on when this enhancement will be in production? 

![image](https://user-images.githubusercontent.com/4256979/114603659-ff130a80-9c65-11eb-8a51-16aeaaa1dd5a.png)

**Comment by IsmaelInRedlands** [comment]
Currently planned for July 2021.

**Comment by pjdohertygis** [comment]
Implemented v1.11
