### ISSUE TITLE
QuickCapture drawing simple lines on Android

### ISSUE THREAD

**Issue by pjdohertygis** [pjdohertygis/WideAreaSearchTemplates#128]
Device Type: Samsung S21 5G (SM-G991U)
Device OS: android 11.0
Device App Version: QuickCapture 1.9.136

QuickCapture Project hosted in ArcGIS Online can be accessed anonymously here
https://arcg.is/14fK4

Issue: The tracklog is only collecting new vertices when the app is actively open on screen. It is drawing a straight line between when it was first started and when the app is opened again. 
![image](https://user-images.githubusercontent.com/4256979/114607762-e9ecaa80-9c6a-11eb-921c-003bf41e381a.png)
![image](https://user-images.githubusercontent.com/4256979/114610094-887a0b00-9c6d-11eb-9680-45520e068390.png)

Settings:
![image](https://user-images.githubusercontent.com/4256979/114607735-e2c59c80-9c6a-11eb-9723-1b61b46c9095.png)

@IsmaelInRedlands I believe that the QuickCapture Team fixed this for Pixels, but now maybe it is popping up on other Android devices? https://community.esri.com/t5/arcgis-quickcapture-questions/quick-capture-tracking-stop-in-background/td-p/1024805

**Comment by pjdohertygis** [comment]
Ok this is a known issue and Esri is working on it as of 4/13/21.

**Comment by pjdohertygis** [comment]
Today the same user as above (AZ-TF1) said that something improved. 

![image](https://user-images.githubusercontent.com/4256979/114642303-b416e880-9ca1-11eb-8698-542bd02bb3c0.png)


"I did another test during my run tonight.  A screenshot is attached.  The purple lines show the one I did last week that did NOT work correctly.  I laid 3 tracks today and you can see that they are all much better.  I did one of them in airplane mode and the other 2 with good data connectivity.  I see no difference in the ability of the app to capture the track.  I had the phone powered ON with the screen OFF in my pocket and I made sure to minimize the app and open another app before turning off the screen just to make sure.  I don't know if it was an upgrade or something that fixed the problem between then and now, but I was unable to recreate the failure today.

**Comment by JohnHasthorpe** [comment]
@IsmaelInRedlands Background location now works on all versions of Android. However, if the app is in background and the device is stationary (e.g left on a desk), Android can suspend regular location updates in order to preserve battery. In this case, location updates are instead sent through in batches and this is not supported by AppStudio. There is an issue open to address this, but no firm timeline.

**Comment by pjdohertygis** [comment]
@JohnHasthorpe For now, until there is a fix, is there is a way to stop this behavior if we go into android developer mode on the device and adjust the background sleep / GNSS settings?  We do a lot of stopping and waiting during missions so this could be an issue if we don't have a workaround. - From Jason W on MO-TF1.

**Comment by pjdohertygis** [comment]
It sounds like there are multiple causes for this behavior. 
- Bug: Specific to Android Pixel - resolved.
- Stationary Android / Background location - open issue, will update here when addressed. @JohnHasthorpe
