### ISSUE TITLE
QuickCapture: iPhone 8 failing to upload tracks - Troubleshooting Tips

### ISSUE THREAD

**Issue by pjdohertygis** [pjdohertygis/WideAreaSearchTemplates#129]
On the FEMA hosted QuickCapture project, failing to submit tracks from Jonathan's (CATF6) iPhone 8. 

iPhone 8
iOS 14.4.2
QuickCapture v1.9.127
Signed-in catf6_tis
Project: https://arcg.is/1PmzO90 (requires login)

Waypoints are submitted but the tracks just say "sending".

He exits the project and then comes back to it - still sending. 
He then closes the app entirely, opens it back up, and is able to send the tracks. Successful. 

@IsmaelInRedlands - we will try to reproduce.

**Comment by IsmaelInRedlands** [comment]
Should this be closed for now and reopened in the future if we have a repro case?

**Comment by pjdohertygis** [comment]
Agreed - closed
