### ISSUE TITLE
QuickCapture: Bug where app freezes when editing location (low memory)

### ISSUE THREAD

**Issue by pjdohertygis** [pjdohertygis/WideAreaSearchTemplates#131]
Johnathan from Esri thinks this is a separate issue. 

"Here is feedback from CA-TF7

Hi Paul,

I would be more than happy to help out with troubleshooting.

Situation- over a three-day period we had six drills on data collection. We were using the iPad mini 5, model number MUY82LL/A, and ArcGIS QuickCapture version 1.9.127. Approximately 150 people used these devices to collect data. We started in the classroom; I instructed all users to turn off the wifi, we left the building started a search track, walked about 1000' to a track. I had set up 20 pictures of disasters and attached them to a chain link fence. Each picture was approximately 15' from each other. Each picture had information for the students mark waypoints and preform data collection. Each class had +/- 20 students. After the data collection we walked back to the classroom and viewed the collected information on the dashboard.

Issues:
• On occasions, when using the pencil and trying to zoom into a location the app would freeze. We were unable to move out of the map area and would have to double click the circle on the device and close the app. This happened numerous times, almost at each drill.
• After relaunching the app. We lost the tracks. I looked at the dashboard and it appeared that the tracks were not saved after the app froze.
• Some of the students forgot to click on the search icon again after the search was completed and then closed the app. I believe those tracks were lost.
Hope this helped. let me know if you need anything else. Thanks."

**Comment by pjdohertygis** [comment]
From John "So you have a workaround, which is to use a webmap that only has the imagery layer (not hybrid or labelled). But I would like to see if the user would test the TestFlight 1.10 build to see if this makes any difference."

**Comment by IsmaelInRedlands** [comment]
Update from QuickCapture team at Esri: We will likely need to push back resolution of this issue to early 2022. We had plans to work on this for our December update but the implementation of location tracking is going to take all the dev team we have for the Dec release.

**Comment by IsmaelInRedlands** [comment]
This issue should now be addressed in the Beta 1.13 builds.  Planned delivery date early March 2022.  When editing records the map now launches much faster and the memory footprint has been reduced.

**Comment by JohnHasthorpe** [comment]
@pjdohertygis is this still an issue for you?

**Comment by pjdohertygis** [comment]
> @pjdohertygis is this still an issue for you?

I have not seen it with any devices I test. 

@jdokemaps @afackler how about on your Androids?
