### ISSUE TITLE
QuickCapture: Bug where tracklog is not saved when force closing the app. 

### ISSUE THREAD

**Issue by pjdohertygis** [pjdohertygis/WideAreaSearchTemplates#132]
When the user (CA-TF7) closes a project without ending lines, the app should save all lines. This is not a crash situation, but a manual close. This is broken in 1.9. This will be a fix in 1.10.

**Comment by pjdohertygis** [comment]
@IsmaelInRedlands @xiao8579  this was fixed in v1.10 correct?

**Comment by IsmaelInRedlands** [comment]
This should be fixed.
There is no way for the app to know if the app was closed or crashed. For this reason, data will be captured until the point when the app is closed. Data will be sent according to the auto-send rules you have setup.

**Comment by pjdohertygis** [comment]
Thank you @IsmaelInRedlands !
