### ISSUE TITLE
WAS Survey: Victim Confirmed limited to one survey per person

### ISSUE THREAD

**Issue by pjdohertygis** [pjdohertygis/WideAreaSearchTemplates#133]
In January 2021, TX-TF1 recommended we should configure the survey so the end-user can only enter 1 person when submitting "victim confirmed". The reason behind this was that each person that needs rescue requires specific information about where they are.  This made sense at the time and for certain scenarios (when there are few victims, when there is an "incomplete rescue"). 

We made this change for v8, but this needs to be reversed. 

Reason(s): 
- Inefficient / Impractical for scenarios with larger quantities of people (e.g., earthquakes, floods in large urban areas) see scenario below. 
- This is confusing some TF members since they were under the impression we no longer needed to collect a waypoint for each person. How do we explain/justify this right on the Survey? Is this really the right approach? 

Scenario A
What if we arrive at a flooded apartment complex and confirm there are 12 victims that need rescue? You know they are there because of a reliable witness, but you cannot get to them right away. Fill out 12 Surveys?
Scenario B
You have a partially building with confirmed victims but there is no way to confirm the number of people? Someone estimates there are over 50 people in the building...fill out 50 Surveys with incomplete information? 

We had several Task Forces in California run this through their field exercise and provide feedback that this is "just as bad as Iron Sights".

**Comment by pjdohertygis** [comment]
For now, we have turned on the ability to enter multiple victims back on in Survey123 with hint text.

![image](https://user-images.githubusercontent.com/4256979/122628777-10650280-d06d-11eb-8658-007b1ab3e2ba.png)

**Comment by fytfyr5150** [comment]
My question is... If we add the ability to add the number count with 1 survey back then it would stand that those teams that want to do 1 per confirmed victim could still do that but just leave the number as 1. 
That would address both sides of this discussion. 
Now this doesn't fix the system issue of what it all means and looks like on the dashboard but at the same time this is a tool for the teams to use to document what "they" did and help coordinate their searches.

**Comment by pjdohertygis** [comment]
From CA-TF6

CA-TF6 comments on Data Collection Protocols 
Benefits of the original protocols (v7 - allowing multiple people per entry) was not having to collect surveys for each individual victim this was always a complaint on our original Iron sites system. The time it takes for boots on the ground to input for each individual victim was and is time consuming and slows down our efficiency as rescuers. We understand how important our data collection is but at the same time we are here to rescue and get the citizens out of harms way.
V/R
BillyM 
CA-TF6

**Comment by fytfyr5150** [comment]
PJ,

Making sure you got mine.




*My question is... If we add the ability to add the number count with 1
survey back then it would stand that those teams that want to do 1 per
confirmed victim could still do that but just leave the number as 1.That
would address both sides of this discussion.Now this doesn't fix the system
issue of what it all means and looks like on the dashboard but at the same
time this is a tool for the teams to use to document what "they" did and
help coordinate their searches.*
Bubba

**Comment by pjdohertygis** [comment]
@fytfyr5150  We added the ability to specify a number of persons back to the Survey - if a Task Force wants to use one survey per person (which totally makes sense in some situations) they can still do this by entering the number 1 and filling out additional surveys. We added a note specifying this, so we should be good to go now. Feel free to update your Sandbox Survey123 and test, let us know what you think. 

The bigger question is.... for QuickCapture - should we force them to Survey123 when they choose human interaction questions? https://github.com/pjdohertygis/WideAreaSearchTemplates/issues/135

**Comment by fytfyr5150** [comment]
I would say YES to #135.

Those are critical pieces of collected info that I feel we need detail on.
Or at least the option to add detail.

**Comment by jdokemaps** [comment]
We removed the constraint to only have one person per waypoint for Victim Confirmed and Human Remains Confirmed. The person count still defaults to 1 but can be increased as necessary. This leaves the choice with the Task Force on how to deal with it.

**Comment by pjdohertygis** [comment]
FYI with regards to QuickCapture, I turned off comments and switched all human interactions to person count for button user input. The comments will say "Entered with QuickCapture - add comments later". This will reduce the likelihood of PII entering the system and allow them to more quickly enter data. We can use the rules of engagement and linked buttons to force them to use Survey123 when we need more details. Let's test this out on the Sandbox for now and revisit after it has been through a few exercises.
