### ISSUE TITLE
Experience Builder: Refine the layout, use pages and sections

### ISSUE THREAD

**Issue by pjdohertygis** [pjdohertygis/WideAreaSearchTemplates#134]
Based on the trajectory, we are going to have a demand to add more apps and resources to the Deployment / Sandbox landing page. To cope with this, we are exploring using the same approach as NZ's "GRIP" layout. See below. It is clean and allows for expanding complexity without overwhelming the user.

![image](https://user-images.githubusercontent.com/4256979/122603500-48e2ed00-d029-11eb-8f1a-94381a97ac39.png)

**Comment by CLivingstone** [comment]
![image](https://user-images.githubusercontent.com/76217195/122603698-c23b0980-d042-11eb-8401-6d29b8233ad2.png)
Here is a prototype of what the USAR deployment page could look like, following the NZ example.

**Comment by pjdohertygis** [comment]
We have added this into Planner to work on this winter - by the way this looks awesome @CLivingstone

**Comment by pjdohertygis** [comment]
Here is an example configuration --- 

The pages appear on the left and the sections are tabs across the top. So we think the Pages will be listed by "Role" and the Sections will be "Tools". 

![image](https://user-images.githubusercontent.com/4256979/145493246-decd6efe-832b-447e-9a0a-7270ce5a8926.png)
