### ISSUE TITLE
Tactical Dashboard: Live Trapped vs Live Removed

### ISSUE THREAD

**Issue by pjdohertygis** [pjdohertygis/WideAreaSearchTemplates#137]
From CA-RTF12 

"The RTF12 GIS Lead observed that dashboard indicators displaying running totals for Live Trapped and Live Removed would be nice.  The USAR responders focus on those totals on the white boards.  Has this been discussed?  Understanding that space is scarce on the monitor and info overload is always a consideration."

Thoughts?
![Uploading image.png…]()

**Comment by pjdohertygis** [comment]
From @CLivingstone 

In the existing WAS Form, the ‘Victim, detected’, ‘Victim, confirmed’, and ‘Rescued’ waypoints would be the closest equivalent to Live Trapped/Live Removed.  In the Strategic Dashboard, the ‘Count of People by Waypoint Type’ provides these numbers.  

In the Tactical Dashboard, one approach would be to create a similar but more focused chart to track the waypoints listed above.  This could also be split out by follow-up status to emphasize that aspect of the workflow, something like this:
 

Regarding the RST and HAZ forms, I had drafted a possible workflow for associating waypoints with a particular structure (see notes here).  This would allow users to select an RST record in the dashboard and see only the waypoints associated with that structure, including the count of Victims detected/confirmed/rescued.  This is probably as close as we could get in our current system to the kind of tallies produces in INSARAG’s ICMS. 
![image](https://user-images.githubusercontent.com/4256979/122653613-b703de80-d113-11eb-8bf7-d17f47387d04.png)

**Comment by CLivingstone** [comment]
This element has been added to the Tactical Dashboards, NAPSG Sandbox and FEMA deployment system.
