### ISSUE TITLE
Training Approach

### ISSUE THREAD

**Issue by pjdohertygis** [pjdohertygis/WideAreaSearchTemplates#138]
From OH-TF1

I'm still trying to figure out a good "training" workflow for teams to use throughout the year. I know it's tough to manage two QC instances both hosted by FEMA, but it's also difficult for other teams (Search, Rescue, Hazmat) to get the NAPSG training version QR code when I'm not there. This will really come into play on deployments where we spend the first staging day getting everybody back up to speed on the apps.

What if we don't rely on a "training" survey at all, and just create another category for Segments, called training, where somebody on the team outlines an area where the training will be conducted, and it has a separate fill color. That way whoever is looking at the data (IST, FEMA office, other TFs, etc) instantly knows that the points are not operational. This will also eliminate the possibility of a team (OH-1) collecting operational data on a non-operational survey. Each team could also designate "permanent" training segments at their training centers, kind of like you did for the 2021 exercise.

**Comment by pjdohertygis** [comment]
We can utilize the Batch Attribute Editor to quickly highlight data as Training / Exercise as well. 

What should happen next? Should the data be filtered from Dashboards by default? Or only during deployments?

![image](https://user-images.githubusercontent.com/4256979/122655706-7a8baf00-d122-11eb-94ed-e4848549bec5.png)

**Comment by grover556** [comment]
How easy would it be to run a script daily or weekly that deleted all points that are inside a Training segment and that are more than one week old? I think the data should show up on the dashboards, so teams can monitor the progress and review afterwards.

Even during an activation, we should be filtering the dashboards by time and extent anyways.

**Comment by pjdohertygis** [comment]
Let's discuss revising the Sandbox vs. Deployment approach this winter. We need to consider that there are now both FEMA and SUSAR Task Forces using the system.

**Comment by pjdohertygis** [comment]
We added the "Delete This" workflow which addresses this.
