### ISSUE TITLE
QuickCapture: Linked button to Survey123 - 2nd time takes you to Outbox, not Survey form

### ISSUE THREAD

**Issue by pjdohertygis** [pjdohertygis/WideAreaSearchTemplates#139]
On a iPhone X, 14.7 running both v1.10 and v1.9, hitting an issue where the 2nd time you use a linked button, it takes you to the Outbox instead of the Survey. Can replicate on two different iPhones. @IsmaelInRedlands 

https://arcg.is/1XfKTe

**Comment by JohnHasthorpe** [comment]
QuickCapture will call the same URL each time, for example the following will be harcoded into the project json for the button: `arcgis-survey123://?itemId=2bcea2b1dae646cca39c204c6b78b706`

Once you launch the survey the first time, what do you do? Do you complete and send it? Do you close Survey123?
Also, can you confirm the Survey123 version you are using?

Thanks
John

**Comment by pjdohertygis** [comment]
When OH-TF1 sent me the issue a few days ago I was able to replicate on a 4G connection consistently on the second attempt using Survey123 3.13.138Beta and QuickCapture 1.10.137 (I think unless TestFlight automatically updated). 

This morning I tried to record on my phone and of course I cannot replicate the issue. I'll check with OH-TF1 to see if they can replicate.

**Comment by grover556** [comment]
I can still replicate this morning using Survey123 3.12.277 and QuickCapture 1.9.127. Happens on a WiFi connection as well as LTE.

**Comment by pjdohertygis** [comment]
Workflow to replicate.

1) open QuickCapture project https://arcg.is/1XfKTe

2) start tracking

3) enter major damage

4) fill out Survey (I had favorites already setup - send

5) go back to QuickCapture and fill out victim confirmed 

6) it opens the outbox (or at least was when I tested it the other day)

At home on wifi I'm no longer able to replicate - perhaps it was a byproduct of a weak internet connection?

**Comment by pjdohertygis** [comment]
@JohnHasthorpe was able to replicate this morning (Australia evening) 

"It happens if you launch Survey123 before the survey first survey is sent. This is a timing issue. I guess Survey123 is busy sending when it gets called the second time, so the Survey does not open."

Short-term workaround is 

"Wait a few seconds before sending the Survey or if they see the outbox, go back to QuickCapture and press the button again."

This should impact us when working offline correct?

**Comment by JohnHasthorpe** [comment]
This is a Survey123 issue - @tedrick, can you take a look at this one - anything that can be done?

**Comment by pjdohertygis** [comment]
Thanks @JohnHasthorpe @tedrick - I'll have to test this one again, it might be resolved?

**Comment by pjdohertygis** [comment]
@grover556 are you able to replicate this one? I can no longer make this happen with QuickCapture v1.12B and S123 v3.13.234 on iPhone.

**Comment by pjdohertygis** [comment]
Fixed with v3.13 unless @grover556 you can replicate?
