### ISSUE TITLE
Tracklog has two Shape Length fields?

### ISSUE THREAD

**Issue by pjdohertygis** [pjdohertygis/WideAreaSearchTemplates#142]
After downloading the 4 archived layers for the tabletop exercise, I was going to publish a web map of the data because it appears to be too large of an area for the Situational Awareness / Snapshot Tool (separate issue). 

However, I am getting an error related to https://pro.arcgis.com/en/pro-app/2.7/help/sharing/analyzer-error-messages/00362-datasets-expose-reserved-field-names.htm

![image](https://user-images.githubusercontent.com/4256979/123099469-376e5c00-d400-11eb-8d51-09bf592ff0c3.png)

@afackler have you seen this before? Is it related to the notebook, ArcGIS Pro, or is there likely a problem with our tracklog feature layer?

**Comment by afackler** [comment]
I haven't seen this yet, but I also have done limited testing with the layers in Pro. I'll see if I can replicate in the sandbox and look for a workaround.

**Comment by pjdohertygis** [comment]
Workaround for now was export as shapefile, removing the fields upon export. Then remove the gdb/feature layer, publish the web map. 

What concerns me more is, is there an issue with our tracklog layer? Or an issue with the script?

**Comment by afackler** [comment]
Did you try a manual export of the tracklog and seeing if have the same error when working on it in pro?

**Comment by pjdohertygis** [comment]
So far, on the master feature layer itself - there is only one shape_length field 

![image](https://user-images.githubusercontent.com/4256979/123123520-e452d400-d414-11eb-8af3-ec8c21d66b9c.png)

I export it as gdb from the item - then publish the gdb from the gdb item and.... the resulting feature layer has an additional shape field, but it is called shape_length2
![image](https://user-images.githubusercontent.com/4256979/123124061-588d7780-d415-11eb-882e-2018a30b2be5.png)

**Comment by pjdohertygis** [comment]
In order to publish the tracklog layer for the archive - I did a "repair geometry" (not sure if that helped) and then used the Delete Field geoprocessing tool to delete the 2nd Shape_Length (it wouldn't let me delete from the field table). That appears to have worked.  
![image](https://user-images.githubusercontent.com/4256979/123142215-2dac1f00-d427-11eb-87e5-ce8a8d7681f8.png)

This is making me think there is a problem with the feature layer itself. I am going to run "optimize drawing" after I delete out the exercise data and hopefully this is resolved next time.

**Comment by afackler** [comment]
I'm thinking it's the layer too... I tried with several layers in the sandbox (both manual export and through the script) and wasn't able to duplicate the issue on anything

**Comment by pjdohertygis** [comment]
We checked tracklog layer for both FEMA and NAPSG and only see one shape field. We will check next time we make an archive to see if that causes it. Closing for now.
