### ISSUE TITLE
Survey123 Webhook URL

### ISSUE THREAD

**Issue by grover556** [pjdohertygis/WideAreaSearchTemplates#154]
I brought this up over 6 months ago in a Community forum, but it hasn't received any attention...

The Payload URL field for a Survey123 webhook will not allow an IP address instead of a domain name. I need to be able to connect a webhook to a server that has a static IP and does not have a public DNS entry. Entering an IP address provides an error, "Please input a valid URL." An example url, `http://8.8.8.8/api/test` is not accepted, but `http://google.com/api/test` is accepted.
<img width="500" alt="bad" src="https://user-images.githubusercontent.com/62857444/125122881-fe9eda00-e0c3-11eb-9751-e1f5c8993c4c.png">

**Comment by IsmaelInRedlands** [comment]
@pjdohertygis  @grover556   This is planned to be fixed in November 17, 2021.

**Comment by IsmaelInRedlands** [comment]
@grover556  @pjdohertygis  We will push the fix to the beta build of the website on November 5. To test this out, simply flip the URL to survey123beta.arcgis.com...

**Comment by pjdohertygis** [comment]
@IsmaelInRedlands @grover556 I'll pretend to know what you are talking about above... is this resolved?

**Comment by IsmaelInRedlands** [comment]
This should be resolved now. No need to use Beta. @pjdohertygis

**Comment by grover556** [comment]
I can confirm that this has been resolved
