### ISSUE TITLE
QuickCapture - No longer able to add icons to linked buttons?

### ISSUE THREAD

**Issue by pjdohertygis** [pjdohertygis/WideAreaSearchTemplates#159]
Does it appear we can no longer add icons or images to linked buttons in QuickCapture? When I go to add the button, it lets me click Add - Upload New, but then never appears? 

![image](https://user-images.githubusercontent.com/4256979/129907277-122f93a1-0c38-44a2-9ac5-4c11595d8e6a.png)

@xiao8579 is this a known issue or should we report it?

**Comment by xiao8579** [comment]
Hi @pjdohertygis can you check the format of the image, see https://doc.arcgis.com/en/quickcapture/faq/faq-prepare.htm#anchor11

A known limitation is that if the image is of .jfif format, it won't display on the button. A simple workaround is to open it with Paint and save it as .png or .jpg

**Comment by pjdohertygis** [comment]
@xiao8579 I thought that might be it - but the format is .png. Here is the error I receive.
![image](https://user-images.githubusercontent.com/4256979/130122807-271d879d-09e5-4079-862f-430d3d5eaea8.png)

It looks like it is working for me with other projects that I own - but this one is "Shared with me". I am an admin so can usually make changes to projects @jdokemaps owns, but maybe I can't images to buttons for projects I do not own? I'll ask Jared to test when he gets a moment.

**Comment by xiao8579** [comment]
@pjdohertygis Ah ok, now that you mentioned the project is shared with you, I think this is likely a bug on our end. I will raise an issue and address it in the v1.11 ( Sep 2021) release. Thanks again for the feedback!

**Comment by jdokemaps** [comment]
@xiao8579 @pjdohertygis I was able to add the image to the linked button. Must be because I am the owner.

**Comment by pjdohertygis** [comment]
Thanks @xiao8579 - not urgent on our end as we can work around it, but thank you for addressing it!

**Comment by xiao8579** [comment]
Hi @pjdohertygis @jdokemaps, this issue is fixed in the upcoming 1.11 release.

**Comment by pjdohertygis** [comment]
Fixed with v1.11
