### ISSUE TITLE
[ENH] QuickCapture - Default Offline Basemap stays on while tracking

### ISSUE THREAD

**Issue by pjdohertygis** [pjdohertygis/WideAreaSearchTemplates#166]
After v1.11 Default Basemap staying on while tracking even after going back online 
a.	Start creating a line 
b.	Go offline
c.	Accept Default Basemap (the low resolution continent map) 
d.	Go back online
e.	You are still forced to use the Default Basemap until you stop tracking, close the project, and then open the project.

**Comment by pjdohertygis** [comment]
From QuickCapture Team 

"In terms of the default map, this is a fallback used when the project is opened offline. If the user goes back online, the user will need to close and re-open the project in order to access the original webmap. We adopted this approach to keep things simple and make the UX robust. I wonder if once we implement the single map for mapping/editing this may be less of an issue? We welcome further feedback.

We are planning to allow the default basemap to be configured as an organization setting. But this would be an app-level map, not a project one. So the admin would set the item id of the offline map (mmpk, vtpk or tpk) and the app would download it after app install. This would then be used in place of the esri_default map."

**Comment by pjdohertygis** [comment]
@xiao8579 do you anticipate this will be fixed with v1.12 or 1.13?

**Comment by xiao8579** [comment]
@pjdohertygis this is not in 1.12. But will take a look in 1.13 and we may reach out back to you to verify the design before we implement it.

**Comment by pjdohertygis** [comment]
@IsmaelInRedlands (sorry for some reason cannot tag Jonathan H) - I think the above has been fixed? I'll do some testing on my end but let me know I can close this one.

**Comment by pjdohertygis** [comment]
I think the new Reload button handles this well, I'll close this.
