### ISSUE TITLE
Enhancement: Auto-populate fields for State and County

### ISSUE THREAD

**Issue by pjdohertygis** [pjdohertygis/WideAreaSearchTemplates#17]
What is the best approach for this? 

- Reverse geocoding in the Survey? Does this require internet? Does it cost credits / how much? https://community.esri.com/groups/survey123/blog/2018/07/06/understanding-reverse-geocoding-in-survey123-30
- Arcade field calculation? Is this possible?

**Comment by IsmaelInRedlands** [comment]
I would go with reverse geocoding. Here is an example XLSForm.  This uses the Esri locator which consumes [ArcGIS Online credits](https://www.esri.com/en-us/arcgis/products/arcgis-online/pricing/credits).  To use the XLSForm below users will need to be signed in when using Survey123. Alternatively, you can create a locator service with ArcGIS Server and use it for your reverse geocoding. That would not consume any credits. 

[AutoCalculateZIPCountyState.xlsx](https://github.com/pjdohertygis/SARandFirstResponderSurvey/files/3602872/AutoCalculateZIPCountyState.xlsx)

**Comment by pjdohertygis** [comment]
Thanks Ismael - in either case (AGOL or AGS) would this cause an issue when they work offline? Would they hit an error or could they proceed without the geocoding connection? Would it impact performance of the Survey?

**Comment by IsmaelInRedlands** [comment]
When working offline they will not get any suggestions.
No impact on performance. When offline, the function does not even trigger a request to the server.

**Comment by jdokemaps** [comment]
@pjdohertygis Since a lot of the SAR workflow will occur offline, we will have to run a process on the County and State fields anyway to populate the data that was collected offline. Because of this, I think we will not do a reverse geocode for County and State. We will create one for "Address" since that is "bonus" information that can't be easily populated nationwide on the backend.

**Comment by jdokemaps** [comment]
We are not going to include this in v7. May be something we come back to in later versions.

**Comment by pjdohertygis** [comment]
We are investigating how to use scripting to autocalculate Address, County, State. 
- Arcade calculation - waiting on Esri to fix a bug
- Jupyter Notebooks?

**Comment by pjdohertygis** [comment]
Josh Keller has a script we can use for reverse geocoding and I believe Tim Mahon is adding it to the ArcGIS Pro template. Let's close this issue once confirmed.

**Comment by pjdohertygis** [comment]
Transferred to Planner https://teams.microsoft.com/l/entity/com.microsoft.teamspace.tab.planner/tt.c_19:WQQU-GLBt5PUCaamNqbuPkjLTt8tsICkDpvbXmW_T541@thread.tacv2_p_PQ35VCIfNU2Eeb0TdloUJmQADk0f_h_1636482835657?tenantId=e78bd32c-e20a-42de-9956-6429fc41698d&webUrl=https%3A%2F%2Ftasks.teams.microsoft.com%2Fteamsui%2FpersonalApp%2Falltasklists&context=%7B%22subEntityId%22%3A%22%2Fboard%2Ftask%2FaTw1o4viVkisxZcHWMNUOWQAOCZs%22%2C%22channelId%22%3A%2219%3AWQQU-GLBt5PUCaamNqbuPkjLTt8tsICkDpvbXmW_T541%40thread.tacv2%22%7D
