### ISSUE TITLE
Survey123: Rescued - Person Count limited to 2 digits

### ISSUE THREAD

**Issue by pjdohertygis** [pjdohertygis/WideAreaSearchTemplates#179]
VA-TF1 pointed out that the person count for human interactions is limited to 2 digits. If there was a nursing home with 102 people, they wouldn't be able to use this. 

I recommend we change to 3 digits.

**Comment by pjdohertygis** [comment]
@afackler can you dig into this? I think there might have been a technical reason why this was limited to two characters but neither Jared or I remember why...

**Comment by afackler** [comment]
Looks like the D0 in the Body Esri Input Mask field for that question is preventing more than 2 characters. I asked Jared about it and he said it was to prevent negative numbers to be put in. However, I found if you put another 0 in, making it D00, you can have 3 characters and no negatives. I implemented this into the sandbox earlier today.

**Comment by pjdohertygis** [comment]
Let's keep an eye on usability issues with the two blank spaces but I will close this issue for now.
