### ISSUE TITLE
[ENH] QuickCapture: Map Feature Request - Layer list

### ISSUE THREAD

**Issue by grover556** [pjdohertygis/WideAreaSearchTemplates#187]
Had a few people from OH-TF1 requesting the ability to toggle layer visibility in QuickCapture. It is difficult to identify/read the segment layer label when there are lots of point features in and around.

**Comment by xiao8579** [comment]
Hi @pjdohertygis @grover556 Could you help clarify it further- are there any other map components that you need? We had heard about map scale bar, ruler, feature label, layer visibility toggle, and feature pop-up/attributes? And how would these help with the current data capture workflow and why? It will help us boil down the requirements and design on our end.

**Comment by grover556** [comment]
Hi @xiao8579 I'm not sure how busy we want to make the map within QuickCapture, but the layer toggle need is for the following scenario. Right now, we divide a town or neighborhood into segments and assign those to individual squads for completion. Due to the density of points, it's difficult (if not impossible) to locate or read the segment label and boundaries on the map because it just gets lost in the clutter. If users can toggle the point layer on/off, they can quickly view the boundaries of the segment they're assigned to.

I think a basic scale bar would be useful in the map view, and perhaps a ruler, but I'm not sure the need for feature popups is there. We already have labels enabled for polygons, so that's taken care of.

One thing that has developed in my mind while writing this, may be more appropriate as a separate enhancement request is to be able to long-tap on the map to "Collect here" just as is possible in Field Maps. Confirming the "collect here" would just bring up the primary QC page/menu but remember the coordinates of the map. We do a lot of point-dragging after collection to ensure it's on top of a structure, but this would save a step in that process of thousands of points collected.

**Comment by pjdohertygis** [comment]
This has been implemented with v1.18 @grover556
