### ISSUE TITLE
Targeted Search taskings

### ISSUE THREAD

**Issue by grover556** [pjdohertygis/WideAreaSearchTemplates#188]
On the last deployment, we had a large queue of buildings needing secondary K9 searches. In lieu of TFs not officially being able to edit in Field Maps, I propose splitting Targeted Search into two: Target Search Task (TST), and Target Search Clear (TSC). Target Search Task's QC question would be the type of search requested: "K9 LF" "K9 HRD" "Search Cam" "Other", which will populate the notes field. The follow-up field would be automatically recorded as "Assigned" or "Completed", but not sure which.

Workflow:
A rescue squad would mark a waypoint at an area/building needing specialized search, and can move on continuing to other structures. The TSS or K9 can utilize Field Maps or QuickCapture to navigate to the TST waypoints, and then mark a TSC waypoint when the search is complete.

**Comment by pjdohertygis** [comment]
Let's raise this with Cadre since this would involve a change in the data model. 

We can explore using Workforce for these use cases. I'd hate to add another app to the arsenal.

**Comment by pjdohertygis** [comment]
This should now be resolved with editing in Field Maps!
