### ISSUE TITLE
QuickCapture - Provide PDA Damage Category definitions for each waypoint button

### ISSUE THREAD

**Issue by pjdohertygis** [pjdohertygis/WideAreaSearchTemplates#194]
From IN-TF1 Program Manager

"1.	When in the program Damage Assessment buttons: Minor to Destroyed buttons being able to click on them once to show the definition and then click twice identify the structure.  Then put a reminder to drag pin to the “A” side of the building."

"4.	See comment #1, but for Human interactions, Hazard and other support buttons could all have definitions on the first click and the selection on second click.  It would provide more accurate information while collecting field data. "

Our Response

- With regards to making the definitions available with each button, I like this idea of keeping the definitions at their fingertips. We cannot enable this type of single / double click interaction (although we will pass this on the Esri) but I think we can put a hint under the Damage Comments question (“button user input”). This will provide a little more feedback before they commit to entering the point. 

- With regards to “put a reminder to drag pin to the “A” side of the building.” – this is planned with the next release of QuickCapture v1.13. The user will be prompted with a map for questions we choose and I believe there will be an optional message we can configure. https://github.com/pjdohertygis/WideAreaSearchTemplates/issues/99

**Comment by pjdohertygis** [comment]
@afackler - I'll add this to Planner today and we can discuss what we can do in the short-term. 
@IsmaelInRedlands - interesting feedback above worth considering? Any other suggestions on what we can do now?

**Comment by pjdohertygis** [comment]
Short-term fix --- Button User Input Comments

![image](https://user-images.githubusercontent.com/4256979/147508633-4cb71b81-aec4-43e3-9394-4f12883f79a8.png)

![image](https://user-images.githubusercontent.com/4256979/147508588-f09acf0b-4bc0-41ec-9b93-370fdae6acd4.png)

Destroyed: the home/structure is a total loss.
Major: a home with structural damage or other significant damage that requires extensive repairs.
Minor: a home with repairable non-structural damage.
Affected:  a home is considered affected if the damage to the home is mostly cosmetic.
Unaffected: No visible or suspected damage, likely outside the impact area.

**Comment by pjdohertygis** [comment]
Instead of relying on the hints, we are going to try adding definitions right to the buttons. Feedback? 
QuickCapture https://arcg.is/14fK4

![image](https://user-images.githubusercontent.com/4256979/149553786-e0cf717e-1bba-4352-b098-d754567a8959.png)



![image](https://user-images.githubusercontent.com/4256979/149553712-c2108347-a458-4e95-a435-b994e0773531.png)

**Comment by grover556** [comment]
For the QuickCapture v1.13 bullet point, do we have the ability to conditionally require map input based on active search type? For example, we've begun the discussion about requiring map input on certain types of searches and/or waypoints. Lets see if we can require map input for Targeted and Secondary, not for Hasty or Recon, and maybe for Primary. I can see the flip side of having to move a point that doesn't need moved when you're standing where you want to collect.

**Comment by pjdohertygis** [comment]
> For the QuickCapture v1.13 bullet point, do we have the ability to conditionally require map input based on active search type? For example, we've begun the discussion about requiring map input on certain types of searches and/or waypoints. Lets see if we can require map input for Targeted and Secondary, not for Hasty or Recon, and maybe for Primary. I can see the flip side of having to move a point that doesn't need moved when you're standing where you want to collect.

@grover556 I'll move this comment over to https://github.com/pjdohertygis/WideAreaSearchTemplates/issues/99 so it doesn't slip through.
