### ISSUE TITLE
QuickCapture - Screen size issue with iPhone 13 Mini

### ISSUE THREAD

**Issue by pjdohertygis** [pjdohertygis/WideAreaSearchTemplates#198]
![iPhone13 screen size issue](https://user-images.githubusercontent.com/4256979/150800350-6b622c24-497b-4bde-b459-93cd594de941.jpeg)

I don't think any US&R Task Forces have iPhone 13 mini as standard issue yet but... Alix and I noticed on her new phone the user interface is cut off at the top and makes it hard to tap on the map icon. 

Just passing it along in case it is something that can be fixed with v1.13!

**Comment by pjdohertygis** [comment]
It looks like this is being addressed in 1.13.304

**Comment by JohnHasthorpe** [comment]
@pjdohertygis can you get this verified on the testflight build?

**Comment by pjdohertygis** [comment]
@avezina can you test on your fancy new undersized phone?

**Comment by avezina** [comment]
Beautiful
![quickcapture](https://user-images.githubusercontent.com/50338557/152384364-a5ee97ad-7585-4d9f-8b11-22abf432729c.jpg)

**Comment by JohnHasthorpe** [comment]
Thanks for testing
