### ISSUE TITLE
QuickCapture v1.13 - Map Input not showing captures on device.

### ISSUE THREAD

**Issue by pjdohertygis** [pjdohertygis/WideAreaSearchTemplates#200]
IN-TF1 Roger mentioned this problem and I didn't understand until I tried it.

1) Enter a point, use map input to drag pin to structure
2) Enter another point, use map input to drag pin to another structure - while the map is open, then can't see the most recent point entered until it goes up to the feature layer and shows up in the web map. Shouldn't we at least see the "active capture" pin?

The concern is the end user will end up adding two points at the same structure. ![image](https://user-images.githubusercontent.com/4256979/153729482-7ffa5ebb-0fa1-403d-aa1d-3578a8a6aaa1.png)

![image](https://user-images.githubusercontent.com/4256979/153729488-ca97b270-08b7-49cf-95ed-d0f8a9983767.jpeg)

I'll save a video and send on request. @IsmaelInRedlands @xiao8579

**Comment by pjdohertygis** [comment]
I am able to reproduce the behavior on an iPad mini 5th generation, 14.7.1 with QuickCapture v1.13.310. 

It is easier to demonstrate on an iPad because you can see the map the whole time. It almost looks like it is not honoring the autosend feature correctly too. I have it set to send every 15 minutes, but it appears to send me data anyway each time I make an entry using the map input.

**Comment by IsmaelInRedlands** [comment]
Got it. The problem is understood. Thanks a lot. Will discuss with the team Monday. No further repro steps needed.

**Comment by pjdohertygis** [comment]
This appears to be fixed (although I am currently testing v1.15, I think it was fixed in v1.14). Thank you!
