### ISSUE TITLE
QuickCapture v1.13.301 - Firefly in web map issue?

### ISSUE THREAD

**Issue by pjdohertygis** [pjdohertygis/WideAreaSearchTemplates#201]
.@avezina was doing some testing with 1.13.301 and noticed her web map no longer loads on iPhone 11 or iPhone mini 13.
https://www.arcgis.com/apps/mapviewer/index.html?webmap=f44caeec1213412ea7cde8f940d4e487 (private, we can invite to a group)

The error is the message:
"Failed to load the map
 RELOAD
USE DEFAULT"

It does work in production 1.12.104, iPhone 13 mini when she downgrades. 

Could it be Firefly symbology? 
I tried "updgrading" the project with devext but it did not help. 

Web Map screenshot
![image](https://user-images.githubusercontent.com/4256979/153765619-cc85f40a-946f-4dd4-b070-6a74853bf319.png)

![image](https://user-images.githubusercontent.com/4256979/153765641-cf374ea1-5b02-4e33-b2e9-be4208e77c8c.png)

**Comment by JohnHasthorpe** [comment]
@pjdohertygis can you share the map with QCCreator ?

**Comment by pjdohertygis** [comment]
@JohnHasthorpe invite sent!

**Comment by JohnHasthorpe** [comment]
This looks like a runtime bug. Can you share how you created the adventure tracks symbology?

**Comment by JohnHasthorpe** [comment]
Thanks @avezina

**Comment by JohnHasthorpe** [comment]
This will be fixed in 1.15 with the runtime update to 100.14
