### ISSUE TITLE
QuickCapture: Could the Location Tracking "enabled toggle and bar" be moved into the app settings screen

### ISSUE THREAD

**Issue by jwarzinik** [pjdohertygis/WideAreaSearchTemplates#202]
@IsmaelInRedlands  Could the Location Tracking "enabled toggle and bar" be moved into the app settings screen vs along the bottom near the GPS?  As it is now, the banner bar (even when tracking is forced always on) is taking up premium screen area covering up / blocking the usable area of the QuickCapture map/buttons GUI area and users could pretty easily fat finger and turn off location tracking if they are not careful or working too quickly with gloves on hitting buttons

![Screenshot_20220216-135440](https://user-images.githubusercontent.com/91565740/154483957-374960a6-281d-4399-a611-0b7ee2210323.png)

**Comment by pjdohertygis** [comment]
@jwarzinik the only problem I see with the suggestion is you'd have to exit the project to turn it on / off? Maybe there is an elegant solution the QC Team can think about to prevent errant toggling off the tracking.
