### ISSUE TITLE
Larger font for description text and support for Dark Theme

### ISSUE THREAD

**Issue by jwarzinik** [pjdohertygis/WideAreaSearchTemplates#203]
@IsmaelInRedlands  Below is the size of the description text on buttons (which I LOVE to help provide just in time context to the field users) when viewed on a phone with a 5" screen (iPhone mini / XP8 Sonim / etc).  Can the font be increased to be more readable in harsh conditions/bright light. Also is support for "Dark Theme" mode in the works?

![Screenshot_20220216-135404](https://user-images.githubusercontent.com/91565740/154485149-ba94f35c-9725-46f2-9fdb-44db4fed6ebf.png)

**Comment by JohnHasthorpe** [comment]
@pjdohertygis the description in this project is a thumbnail, so we can't do much to change it. What are you thinking?

In terms of dark mode, we have it in the works - but it would only apply to app UI elements and not the project.
Users would need to author a project that was dark theme, but we were thinking of making this easier in the designer with some coloring tools.

**Comment by pjdohertygis** [comment]
@jwarzinik @JohnHasthorpe yep we are experimenting with "hacking" some extra text by creating thumbails with text. It isn't working that well and it might be a nice enhancement to allow people add more text to buttons. Sorry for any confusion!

**Comment by jwarzinik** [comment]
I really like the added text to help the field user, who may only see the app once a year, feel more confident in capturing data correctly.

**Comment by pjdohertygis** [comment]
@jwarzinik I'll send you a note on Teams, I made those thumbnails in PowerPoint. Maybe you can help be tinker with the font size and get it as large as possible? 

![image](https://user-images.githubusercontent.com/4256979/154704084-21d10a95-20ac-41b2-9558-d56179260249.png)

![Recon v1](https://user-images.githubusercontent.com/4256979/154704317-2d69580b-67e9-4a22-a43f-d5c1010c5497.png)

**Comment by pjdohertygis** [comment]
We have done as much as we can on our end to address this, closing.
