### ISSUE TITLE
QuickCapture: Force Split Screen / App Rotation Locked

### ISSUE THREAD

**Issue by jwarzinik** [pjdohertygis/WideAreaSearchTemplates#204]
@IsmaelInRedlands The force split screen setting is intriguing even on phones to give the user a small view of the map at all times for navigation and situational awareness of search progress.  Issue I ran into on the the phones I tested (Samsung s21 and Sonim XP8) which might not be anything you can control, QuickCapture seems to be locked to portrait mode and will not rotate to landscape no matter what I try to do.

![Screenshot_20220216-135754](https://user-images.githubusercontent.com/91565740/154486155-bca7bdee-693d-48c5-89af-b6c530c800da.png)

**Comment by IsmaelInRedlands** [comment]
Agreed 100%
We will likely not be promoting this feature until we can support portrait mode.
It is available in 3.13 Beta, but we may hide for General release until we get this complete.

**Comment by pjdohertygis** [comment]
@jwarzinik sorry I had opened a new issue, can you paste your latest into there

https://github.com/pjdohertygis/WideAreaSearchTemplates/issues/241
