### ISSUE TITLE
QuickCapture v1.13 - Map input slow / sticky upon load on Android

### ISSUE THREAD

**Issue by pjdohertygis** [pjdohertygis/WideAreaSearchTemplates#205]
- @jdokemaps @afackler will add details below on what they're experiencing but basically when they go to use the new map input capability on their Android the map is slow to respond to their pan or zoom when it first loads.

**Comment by pjdohertygis** [comment]
From @jdokemaps "I just tested 1.13.354 and it isn't sticky today"

**Comment by afackler** [comment]
Tested 1.13.354 today as well. Map is still a bit sticky for me, but not as bad as it was (Android version 10 on Galaxy S9+). I am also able to share coordinates but only in MGRS.
