### ISSUE TITLE
Survey123 3.14 and Sandbox Survey crashing on Samsung Galaxy 

### ISSUE THREAD

**Issue by pjdohertygis** [pjdohertygis/WideAreaSearchTemplates#207]
Cross-reference with Esri Case #03017072

ArcGIS Online
Published via Survey123 Connect (confirming version with @jdokemaps )
Survey123 Link: https://arcg.is/0T4mLG
![image](https://user-images.githubusercontent.com/4256979/157765801-4df5c121-b0d9-4d0b-9fa9-93a4dca4a5fb.png)

Web map used in Survey123
https://www.arcgis.com/home/item.html?id=180845d9e64043eabda02214da76729c

AZ-TF1 found an issue with out Survey123 Sandbox today using Survey123 3.14 and a Samsung Galaxy - investigating now. It looks like @jdokemaps can replicate.

![image](https://user-images.githubusercontent.com/4256979/157743240-41467611-8880-4f7f-80f1-2d3fa399e4a2.png)

**Comment by ackelley44** [comment]
Confirmed same crashes on

S123 ver 3.14.237

Samsung Galaxy Tab S3 (SM-T820)

Android ver 9

**Comment by ackelley44** [comment]
Not having crashes here:

S123 ver 3.14.237

Samsung Galaxy Tab A (SM-T387V)

Android ver 10

* This version is NOT giving access to, or using the basemap 6729c Sandbox

**Comment by pjdohertygis** [comment]
Opened Esri Case #03017072

**Comment by jdokemaps** [comment]
Confirmed crashes on Pixel 6 Pro running Android 12 with Survey123 Verion 3.14.237.

**Comment by pjdohertygis** [comment]
IN-TF1 Roger says 

"Paul,

On March 7, the search team was in the IN-TF1 classroom training on QC and S123. They updated the tablets to QC 1.13 and **S123 to version 3.14**. Each person was using both an Apple tablet and **Samsung Galaxy Tab A, Android ver 10 tablets**. Two of the Samsung tablets crashed when plotting a waypoint in QC and **one Samsung tablet crashed when plotting a waypoint in S123.**

All 3 tablets were restarted and not used again.  "

**Comment by afackler** [comment]
Experience some crashes when submitting data and setting favorites. Crashes occurred the most with the first record after opening the app
S123 ver 3.14.237 Samsung Galaxy S9+ Android 10

**Comment by Zachary-Sutherby** [comment]
Hello all, 

We are currently investigating the issue on our end. If possible would you be able to provide a Survey123 diagnostic log when the crash occurs?

**Comment by pjdohertygis** [comment]
@Zachary-Sutherby - I'll work with the team to get some logs. Should I send it to Esri Support and cc you?

**Comment by Zachary-Sutherby** [comment]
@pjdohertygis Yeah that would be perfect, unfortunately it seems I don't have direct access to the Support case, obtaining the logs in an email would work out.

**Comment by pjdohertygis** [comment]
Ok now testing with 3.15.118 and still hitting issue. We have not made much progress with Esri Support and this is critical. Esri Case #03017072 @IsmaelInRedlands @Zachary-Sutherby do you want us to escalate to premium support? 

From @afackler "After my phone updated (still on Android 10), I had a few issues come up: App froze after I exited the map on the location question; Whole app froze and I had to close it entirely to do anything. However, did not happen when I used an Esri stock basemap. The app also crashed when I was trying to save favorites. No issues submitting data"

**Comment by pjdohertygis** [comment]
No longer relevant
