### ISSUE TITLE
QuickCapture: Allow multiple button user inputs

### ISSUE THREAD

**Issue by pjdohertygis** [pjdohertygis/WideAreaSearchTemplates#215]
While we want to keep QuickCapture "quick"... 

We are running into multiple use cases where having multiple button user inputs would be helpful.

1) Damage Assessment - it would be helpful to allow the end user to enter the Address into the address field and then comments. 
2) Victim Confirmed - it would be helpful to allow the end user to enter the number of victims needing rescue and then comments to elaborate on the situation. 

As it stands now, we would have to use Survey123 to accomplish these tasks, but that will take longer and involved having them switch between apps. 

Is there a plan to allow the project author to enable +1 button user input?

**Comment by JohnHasthorpe** [comment]
This is implemented in 1.15

**Comment by pjdohertygis** [comment]
@JohnHasthorpe  I was so excited to hear this, I just checked in QA but still see this? Is there a json hack for it? Or do I just have to be patient and wait for holistic testing? 

![image](https://user-images.githubusercontent.com/4256979/175043667-03eb8e3a-6e07-4abb-94de-d40381e9452e.png)

**Comment by JohnHasthorpe** [comment]
You can test here: https://devext.arcgis.com/apps/quickcapture (sharing/ago.test for the splash screen)
With the test flight build

**Comment by pjdohertygis** [comment]
@JohnHasthorpe - it looks like our QuickCapture Project isn't working well in the devext environment. Notice the data fields are missing in devext, but not in qaext or production.

Dev
https://devext.arcgis.com/apps/quickcapture/project/7ca4485d28d048b58b5741e7c51a3c71/design
![image](https://user-images.githubusercontent.com/4256979/175210710-da1e930c-35e1-4538-9ab7-d1b8f34a6ed3.png)
QA
https://qaext.arcgis.com/apps/quickcapture/project/7ca4485d28d048b58b5741e7c51a3c71/design
![image](https://user-images.githubusercontent.com/4256979/175210777-f71b2cbc-6d03-4cd7-8b68-20e444d967f3.png)
Prod
https://napsg.maps.arcgis.com/apps/quickcapture/project/7ca4485d28d048b58b5741e7c51a3c71/design
![image](https://user-images.githubusercontent.com/4256979/175210890-d14b56cb-ff75-4f3e-af09-49bcc36fb9d8.png)

**Comment by JohnHasthorpe** [comment]
Yes, spotted that and have reported it to the devs. I'll let you know when this is resolved.

**Comment by JohnHasthorpe** [comment]
devext is updated and issue fixed @pjdohertygis

**Comment by pjdohertygis** [comment]
Confirming this works in config and in application. 

SBX/Tracker d14d9a QuickCapture https://arcg.is/8WvSD0

Config
https://devext.arcgis.com/apps/quickcapture/project/4e17b78790fc4120beced44addd14d9a/design
- Choose Victim Confirmed 
- Currently the Button User Input is # of people 
![image](https://user-images.githubusercontent.com/4256979/175540828-afc723c1-7d23-4334-ae24-174df87d10a7.png)
- I am adding an additional for Comments 
![image](https://user-images.githubusercontent.com/4256979/175539803-e624c220-2cac-475e-a5ad-8ab98da2a368.png)
- Creating a new user input type specific to human interactions with Hint: Enter more information here that may be helpful for follow-up. Do not collect PII here!
![image](https://user-images.githubusercontent.com/4256979/175539970-6c127fd5-3357-4242-9289-1db7059e61bc.png)

App on test flight 1.15.34, iOS
https://arcg.is/8WvSD0
![image](https://user-images.githubusercontent.com/4256979/175540541-8ccf0f61-22d3-4dde-ae24-0b0e61897807.png)

Person Count (Button User Input 1) 

Comments (Button User Input 2)

**Comment by IsmaelInRedlands** [comment]
Per discussion August 16, 2022:  We display the button user inputs in the same order you added them into the project. If not happy with the order, delete them and add them again.
