### ISSUE TITLE
Survey123 Linked Button on Android (Pixel) - clears out the Project User Input

### ISSUE THREAD

**Issue by pjdohertygis** [pjdohertygis/WideAreaSearchTemplates#218]
When @jdokemaps uses a Survey123 linked button on our Sandbox QuickCapture - when it returns to QuickCapture it clears out his Project User Input? I cannot replicate on iPhone. 

![image](https://user-images.githubusercontent.com/4256979/169576987-2d0c877d-9783-4a29-8c50-5abd0b5bb80a.png)

**Comment by JohnHasthorpe** [comment]
This is fixed in 1.15

**Comment by pjdohertygis** [comment]
Awesome - @jdokemaps or @afackler can you confirm (you may need to download the apk from EAC)?

**Comment by JohnHasthorpe** [comment]
Yes, grab the latest build on EAC 1.15.XX for Android
