### ISSUE TITLE
QuickCapture 1.15.34 can't click SKIP

### ISSUE THREAD

**Issue by pjdohertygis** [pjdohertygis/WideAreaSearchTemplates#223]
On this project, which I've made some configuration in dev, I cannot click the SKIP button for photos. 

Occasionally, I get asked the same button user input question 2x as well. 

Project https://arcg.is/1TPfOy

https://user-images.githubusercontent.com/4256979/175796107-347fde4d-986e-4545-bb1d-68e9dae8017d.MOV

@IsmaelInRedlands @xiao8579

**Comment by JohnHasthorpe** [comment]
@pjdohertygis - We have a fix for the first issue. Please wait for the next Testflight update.
