### ISSUE TITLE
QuickCapture: v1.15 Project User Input list won't scroll / frozen

### ISSUE THREAD

**Issue by pjdohertygis** [pjdohertygis/WideAreaSearchTemplates#225]
@xiao8579 ill look for you and John at UC, but seeing an issue with v1.15 that won't let us scroll (so far on iPhone, haven't tested Android yet) 

Try it with this project https://arcg.is/01aruG ![image](https://user-images.githubusercontent.com/4256979/178127210-a9cb6cea-cd40-4812-ba27-aa37252e5744.png)

**Comment by xiao8579** [comment]
Hi @pjdohertygis We've noticed the issue and have addressed it in a newer 1.15 build, wait to download a newer build from Testflight. See you around at the UC!

**Comment by pjdohertygis** [comment]
Testing this in 1.15.68 now ![image](https://user-images.githubusercontent.com/4256979/179625270-355fdc99-173f-4b1a-ac05-6ae03511b098.png)

**Comment by pjdohertygis** [comment]
Appears to be fixed in 1.15.68 @xiao8579
