### ISSUE TITLE
QuickCapture: Drop shadow symbology on points - map won't load.

### ISSUE THREAD

**Issue by pjdohertygis** [pjdohertygis/WideAreaSearchTemplates#227]
I'll try to get more details later but looks like they fixed the firefly effect issue https://github.com/pjdohertygis/WideAreaSearchTemplates/issues/201, but drop shadow keeps the map from loading (the map does load in Field Maps with drop shadow). I changed it back for now. @xiao8579

**Comment by xiao8579** [comment]
I've created an issue for this in our backlog

**Comment by pjdohertygis** [comment]
Thanks @xiao8579 not a deal breaker for us, but figured you'd want to know

**Comment by pjdohertygis** [comment]
Resolved
