### ISSUE TITLE
QuickCapture: Partial login issue with public project, can collect but not send data

### ISSUE THREAD

**Issue by pjdohertygis** [pjdohertygis/WideAreaSearchTemplates#228]
When a user uses our "Sandbox" QuickCapture project (shared with Everyone via Hub), they occasionally will hit an issue where they can collect data with QuickCapture but cannot send the data. The end user will go to the map page, click Send, but there is simply no response or message. It just shows that there is data that needs to be sent. 

**The only way to fix this is to know that you need to close the project and go to the "profile" page and sign-in again. The profile will have a tiny orange dot on it**, but the user likely won't see it, especially if they are already in the project.

This may not be a bug, but I do think that is a gap. The end user will have no way of knowing why they cannot send data and assume that it is out of their control. Could there be message that tells them about this issue? It also might be a unique scenario where it is a public project, but a user who has signed-in in the past. 

This happened to me yesterday even though I never intentionally logged out of the app. 

Below is what the user will see if this issue is occurring, the solution is just to sign-in. This is from the June 8th CO-TF1 exercise, sorry I could not get a screenshot. 
![image](https://user-images.githubusercontent.com/4256979/180496504-c9e932c4-3429-48dc-9e0b-0056e985f506.png)

I'll post a video of what I saw yesterday in the comments.

**Comment by pjdohertygis** [comment]
Here is what I saw yesterday - I didn't know what the problem was so did not video the solution - only figured it out afterwards. ![image](https://user-images.githubusercontent.com/4256979/180496923-e3b78c47-c300-4e9d-bd73-7a8af9504696.jpeg)

**Comment by xiao8579** [comment]
@pjdohertygis This could just be a network time-out issue, or user's token expiration. Can you try sending via a good network connection? Or try sign out and sign in again to send? (captured data will not be discarded if you sign out).

**Comment by pjdohertygis** [comment]
Yes I think that may be the cause @xiao8579 - some sort of token timeout. However, the project and services are public so it is an odd behavior. It seems to only happen to those that were at some point signed in. Going to the profile and signing in fixed it. But because the SEND button just doesn't even respond to the tapping, the end user is left confused.

**Comment by xiao8579** [comment]
The app should have displayed a red dot indicator on the user's profile pane to suggest signing in again to refresh the token. This is our current solution in case of token expiration on the app.

**Comment by JohnHasthorpe** [comment]
In 1.15.95 the following error message will display each time a project is opened.
![image](https://user-images.githubusercontent.com/24929507/181421156-7a2a0500-ffbd-4130-aeee-4a21ae1df928.png)
Does that work for you @pjdohertygis?

**Comment by pjdohertygis** [comment]
@xiao8579 @IsmaelInRedlands  any idea how often tokens will expire? We just had a bunch of people get a notice that they're logged out but with no rhyme or reason. They thought maybe it was because we made a minor update to the project but I am guessing the tokens are just on some sort of timer?

**Comment by JohnHasthorpe** [comment]
@pjdohertygis:
- Access tokens - expire every 30 minutes
- Refresh tokens - expire every 2 weeks

The app will try to keep the refresh token alive by getting a new refresh token on opening the app. 
This is the only time that the app will show the orange dot.

Does this sound consistent with what you are seeing? The other thing to check is whether the users are sharing a login.
This could result in all users being affected by an expired/failed access token.

**Comment by pjdohertygis** [comment]
2 weeks makes sense with what we saw a few months ago in CO-TF1 training. But this newer issue almost seems like it is related to the 30 minute refresh token...I'll try to get more details and sent an email to the QuickCapture email.
