### ISSUE TITLE
QuickCapture Beta 1.15.93 - Button user input (comment) Done button not working? 

### ISSUE THREAD

**Issue by pjdohertygis** [pjdohertygis/WideAreaSearchTemplates#229]
I am seeing an issue where the DONE button is somehow stuck or frozen.

![image](https://user-images.githubusercontent.com/4256979/181065323-ac90e5dd-1f68-4307-9688-3efda4467686.jpeg)

![image](https://user-images.githubusercontent.com/4256979/181065348-e1b22557-1999-41e3-b566-f113857d622c.png)

@xiao8579 

In the middle of an exercise will revert back to production.

**Comment by pjdohertygis** [comment]
Confirmed rolling back on the mobile app to v1.14.71 allows me to get to map input screen, but then cannot send data??? 
![image](https://user-images.githubusercontent.com/4256979/181066738-238e9068-4bf4-4c0e-81cb-a209aab3231b.png)

This project was edited in dev. I may save over it in production ArcGIS.com and see if it fixes it.

**Comment by JohnHasthorpe** [comment]
@pjdohertygis - The DONE button issue should be resolved in 1.15.95
