### ISSUE TITLE
Intel Manager 2.0 ExB Add Data widget freezes.

### ISSUE THREAD

**Issue by KeithJGw** [pjdohertygis/WideAreaSearchTemplates#234]
Dell Precision T–5600 Desktop, Chrome Regular or Incognito. In Add Data Search, the Type drop down gets stuck on ‘Curated’ and URL Type drop down gets stuck on ArcGIS Server and the widget freezes.
[Positive; Really convenient that Added layer/s that haven’t been removed are cached/ stored in the Add data widget and can be added back by opening the widget.]

**Comment by KeithJGw** [comment]
The search Type drop down first time noticed was on 11/30/2023. I had added some layers and was trying to search for faults and when I tried to switch to AGOL it hung.
I tried to reproduce and take screenshots then and did. This is right before and reproduced when searching for 'fault line' stuck on curated then.
![20231130_141649_kj SARCOP Intel Manager 2 0 BETA right before repro add data hang on curated](https://github.com/pjdohertygis/WideAreaSearchTemplates/assets/66851958/5b0abcb0-96fb-4536-b7e3-b76c88ec27d9)
![20231130_141750_kj  SARCOP Intel Manager 2 0 BETA add data hang on curated](https://github.com/pjdohertygis/WideAreaSearchTemplates/assets/66851958/3c49c415-0603-443d-b957-f027cb56bd2d)

On December 12, I couldn't reproduce that at all.
On December 13, 2023, search Type drop down happened again and I added it to my notes. I don't recall exactly what I was trying to add though it was likely earthquake, liquification risk, shake hazard, or similar layers and didn't take screenshots.
I tried to reproduce it later, but couldn't. Doesn't happen often, but after the second time I made note of it.

My notes for December 16 has the URL type drop down hang. I had already added several still in the widget layers by just opening the widget; Medical Emergency Response Structures https://www.arcgis.com/home/item.html?id=2c36dbb008844081b017da6fd3d0d28b, USGS_RodgersCreekFaultSection https://www.arcgis.com/home/item.html?id=cd8325d9a66449f9ac5760779cfde9a6, USGS_HealdsburgFaultSection https://napsg.maps.arcgis.com/home/item.html?id=63aeb618421e43c5ba652a8a7a59655d, eq_rodgerscreek (an eq & shake scenario) https://www.arcgis.com/home/item.html?id=ff6b9344a63d41aba7929b0ef78b37e1, Geologic Hazard (a Sonoma County layer) https://services1.arcgis.com/P5Mv5GY5S66M8Z1Q/ArcGIS/rest/services/Geologic_Hazard_Countywide/FeatureServer, Preliminary_Alquist_Priolo_Fault_Zone (a Sonoma County layer) https://services1.arcgis.com/P5Mv5GY5S66M8Z1Q/arcgis/rest/services/Preliminary_Alquist_Priolo_Fault_Zone/FeatureServer/.
Next, I was trying to add a remote kml for an earthquake epicenter location and then a USGS hosted DYFI Geospatial Data, UTM aggregated (1km spacing) geojson https://earthquake.usgs.gov/product/dyfi/nc73781306/us/1696725619658/dyfi_geo_1km.geojson from https://earthquake.usgs.gov/earthquakes/eventpage/nc73781306/dyfi/intensity when URL Type drop down stuck on curated. 
I havent tried to reproduce this often and it seems to happen rarely.

For kicks though I knew it wouldn't work or display, I tried to add a remote kmz hosted at USGS from https://earthquake.usgs.gov/earthquakes/eventpage/nc73781306/dyfi/intensity and was trying to switch from ArcGIS Server to kml and it was stuck on ArcGIS Server.
After a reload of the SARCOP and retry, I could add the kmz via URL and switch to 'kml', but of course it doesn't display as expected.
After that reload, I could add the USGS hosted DYFI Geospatial Data, UTM aggregated (1km spacing) geojson ok.

**Comment by KeithJGw** [comment]
December 20, 2023 afternoon Pacific time I was able to reproduce the add data search hang on curated on a Dell Precision D-5510 laptop on Chrome version 120.0.6099.110 (Official Build) (64-bit) regular session unintentionally.
Opened SARCOP and searched for and navigated to area. Next unticked the layers for Boundaries, and Severe Weather and Tornadoes layer in Live Feed and Hazards Data (MED) then added a bookmark.

Next I opened the widgets going down the ribbon to see where each panel would open. I was looking to see if they all open within the map pane, on the right side of the ribbon in a white margin, or overlapping the widget ribbon and off right screen, or no response without a widget panel opening. I got mixed results.

Then I opened Add Data leaving at Curated and typed in ‘fault’ and one result appeared. Next tried to change from Curated to ArcGIS Online, but it was stuck on Curated.
I deleted ‘fault’ in the search box and still couldn’t change the dropdown. I clicked on several widgets and they wouldn’t open. Opened Add Data and mistyped into search ‘falt’ and couldn’t change the dropdown. Switched to Add Data URL to see if I could change the Type, and it was stuck on ArcGIS Server. I have screenshots during this.
D-5510 laptop froze/ crashed, so I’m adding this via desktop while running diagnostics and if needed can add screenshots.

**Comment by avezina** [comment]
@KeithJGw thanks for the steps, I'm able to see the dropdown stuck at curated. We'll look into it.

**Comment by avezina** [comment]
For later testing, here are the steps to consistently reproduce the behavior:

1. Go to https://experience.arcgis.com/experience/9051a07ffd1947bbb395e9f9b4088f85/page/Intel-Manager-2_0-ExB/
2. Acknowledge the splash and click OK
3. Close the About widget
4. From the Widget Controller (vertical list of widgets on the right), open each widget one at a time and consecutively going down, starting from the Filter widget, until you open the Add Data widget. Widgets to open: Filter > Layers > TF Edit > IST/IMT Edit > Basemaps > Add Data.
5. In the Add Data widget, click to add data
6. From the Search tab, click the dropdown to change from "Curated"
7. Observe: the dropdown does not open

I tried to find if there was a previously opened widget that may be causing this behavior, but I'm only able to reproduce this when I open all widgets described before opening Add Data. We'll see if the dev team can pinpoint the source of the issue.

**Comment by avezina** [comment]
This will be resolved with the February 2024 update of ArcGIS Online.

**Comment by avezina** [comment]
This fix will be released at the end of this month. I am going to close this issue. Let me know if it comes up again.
