### ISSUE TITLE
Camp Event Point photo attachments don't show in Field Maps, Intel Manager 1.0, or 2.0 ExB pop-ups.

### ISSUE THREAD

**Issue by KeithJGw** [pjdohertygis/WideAreaSearchTemplates#236]
Camp Event Point at 10SEH2654453619 photo attachments don’t show in Field Maps pop-up, or in Chrome or Firefox in Intel Manager 1.0 or 2.0 ExB pop-up.
Those attachments show in Field Maps edit, IM 1.0 Smart Editor, & 2.0 TF Edit, and dashboards.

How I came across this. I was editing the Camp point in Field Maps while there and hit an error “Can’t set location; Location is outside the extent of the map.” I think this was a bad cell signal. Waited longer for the map to reload and was able to add the photo. After a wait & refresh, I noticed the photo didn’t show in Field Maps pop-up.
Later added 3 more photos via Field Maps and they didn’t show in pop-up.
The additional 3 show in Field Maps Edit, Intel Manager 1.0 Smart Editor, & 2.0 ExB as Photo 2.jpg, Photo 2.jpg, Photo 2.jpg.

**Comment by pjdohertygis** [comment]
@KeithJGw - simple fix, we just didn't turn on attachments for Event Points in those web maps. 

@afackler I'll address this now.

**Comment by pjdohertygis** [comment]
Fixed
