### ISSUE TITLE
[BUG] QuickCapture: Group Layer Items or group layers with too many layer don't work with QuickCapture

### ISSUE THREAD

**Issue by pjdohertygis** [pjdohertygis/WideAreaSearchTemplates#237]
This is a continuation of earlier testing with Johnathan Hasthore where adding a Group Layer to web map causes QuickCapture to be unstable on iPhone and the map not to load at all on iPad Mini 6th Generation. I believe it is a limitation of ArcGIS Runtime. Just documenting here on Github so we can track and document additional testing. 

Group Layers for testing: 
https://napsg.maps.arcgis.com/home/item.html?id=fcf8c17fdc914b05941baaee1aa35825
https://napsg.maps.arcgis.com/home/item.html?id=0c25d3330e0542d4aca4038cb318e24b

It is unclear at this time if this is cause by the Group Layer item itself OR just having too many layers "grouped" in the web map. 

What is a Group Layer item? 
Blog: [Group Layer Items: A new way to build and share content (esri.com)](https://www.esri.com/arcgis-blog/products/arcgis-online/mapping/group-layer-items-a-new-way-to-bring-your-layers-together/)

Doc: [Organize layers (Map Viewer)—ArcGIS Online Help | Documentation](https://doc.arcgis.com/en/arcgis-online/create-maps/organize-layers-mv.htm#:~:text=Once%20a%20group%20layer%20is,share%20a%20collection%20of%20layers.)

**Comment by JohnHasthorpe** [comment]
@pjdohertygis - we should have a fix for this one. Will share a build for testing once available.

Thanks
John

**Comment by pjdohertygis** [comment]
Resolved
