### ISSUE TITLE
[ENH] - Add Additional Photos to Destroyed, Major Damage, Minor Damage

### ISSUE THREAD

**Issue by jdokemaps** [pjdohertygis/WideAreaSearchTemplates#242]
### Which app?

QuickCapture

### Describe requirements

During some incidents, such as tornadoes in South Carolina, there is a requirement to add photos for each side of a damaged structure. Request to up increase the number of photos per structure to 4 for Destroyed, Major Damage, and Minor Damage. 

### Alternatives

You could use Field Maps to add additional photos and additional attachments. You can also use Situation Update to add more photos. 

### Other Relevant Info

This was also requested by North Carolina. 

### Priority impact

p1 - time sensitive

**Comment by pjdohertygis** [comment]
NC-SAR says "Yes, our focus was to have a photo of all 4 sides of the structure and whatever was causing the damage categorization if it wasn't visible in the first 4 pictures.  For example, the 5th photo maybe a close up of the water line that shows it was 3' high in the structure.  The water line may not be visible or clear in the other photos.   Our request was to allow up to 5 photos."

I have bumped it up from 4 to 5. We can monitor performance of feature layer on the next incident if needed. We do have it set to 1280 px at the moment.

![image](https://github.com/pjdohertygis/WideAreaSearchTemplates/assets/4256979/04c74a2a-fa3d-4faf-a6e6-1d94610ff098)

**Comment by pjdohertygis** [comment]
Resolved
