### ISSUE TITLE
[BUG] - Sandbox Tactical and Strategic Dashboards Map Legend and Basemaps blank after features load

### ISSUE THREAD

**Issue by KeithJGw** [pjdohertygis/WideAreaSearchTemplates#249]
### Which app?

Dashboards

### Describe the Device, Operating System, and Browser

Dell Precision PC & laptop Windows 10 Pro 64-bit; Chrome Version 122.0.6261.129 (Official Build) (64-bit), Firefox 123.0.1 (64-bit), Microsoft Edge Version 122.0.2365.80 (Official build) (64-bit), Regular and Incognito/ Private sessions.
Dell Laptop Windows 11 Home 64-bit; Chrome, Edge, and Firefox current versions Regular and Incognito/ Private sessions.

### Describe the bug

After the Tactical and Strategic Dashboard loads fully, when clicking on Legend or Basemaps they only show the title and none of the legend symbology nor the basemap gallery.
I was able to reproduce this on Win 10 on a desktop and a laptop and Win 11 laptop in Chrome, Firefox, and Edge in regular and Incognito/ Private sessions.
If you hit refresh, then before the features load completely click on Legend or Basemaps it will appear
Yet, after it finishes loading, clicking on them just shows the title and no symbology or basemap gallery.

![20240312_202404_kj SACOP Tact After map pane load no Legend](https://github.com/pjdohertygis/WideAreaSearchTemplates/assets/66851958/6eba6ce3-2106-4f26-8ea2-988c70aceff5)
![20240312_202442_kj SARCOP Tact After map pane load no Basemaps](https://github.com/pjdohertygis/WideAreaSearchTemplates/assets/66851958/e0d19e60-70a1-4717-a056-84a6dd27a24b)
![20240312_204148_kj SARCOP Tact After refresh and before features load Legend 1](https://github.com/pjdohertygis/WideAreaSearchTemplates/assets/66851958/de25ab4f-9ee2-48dc-a91b-91ff48fb3ea7)
![20240312_204151_kj SARCOP Tact After refresh and before features load Legend 2](https://github.com/pjdohertygis/WideAreaSearchTemplates/assets/66851958/bb5c3b0b-576d-47fb-9546-8bc1325347cb)
![20240312_204217_kj SARCOP Tact After refresh and before features load Basemaps ok](https://github.com/pjdohertygis/WideAreaSearchTemplates/assets/66851958/3e9f1f4e-4a01-441b-adaa-b421c6d313c8)
![20240312_204229_kj SARCOP Tact After features load, only title no symbology](https://github.com/pjdohertygis/WideAreaSearchTemplates/assets/66851958/d6e199fe-548c-43cc-b635-3f99eb0f302d)
![20240312_204232_kj SArCOP Tact After features load, only title no Basemap gallery](https://github.com/pjdohertygis/WideAreaSearchTemplates/assets/66851958/150eb066-627f-4212-b9bf-488d3500515f)

### Expected Behavior

Expect to see the symbology in the Legend and Basemap gallery after clicking on either.

### Reproduction Steps & Sample

1. Go to SARCOP Sandbox Tactical or Strategic tab.
2. Wait until page and map pane loads completely.
3. Click on Legend or Basemaps only title appears.

### Priority impact

p0 - not time sensitive

**Comment by pjdohertygis** [comment]
@KeithJGw
@jdokemaps @oviera-napsg and myself all tested this today and cannot replicate in any browser. We were able to replicate it this morning but it is possible a Chrome/Chromium update broke it earlier and fixed it today. 
https://chromereleases.googleblog.com/2024/

Can you confirm on 03/13 if you still see this issue or no longer see this issue?

**Comment by KeithJGw** [comment]
Can confirm no longer seeing that now in any browser regular or private session. Apparently, what ever update rolled out this morning resolved that issue as well as another I saw where I couldn't get pop-ups for waypoints and other features, but that's ok now, too. Which is good as I thought they were related and didn't enter that one.
We can close this out.

**Comment by pjdohertygis** [comment]
Fixed
