### ISSUE TITLE
Create Change Log for Survey

### ISSUE THREAD

**Issue by jdokemaps** [pjdohertygis/WideAreaSearchTemplates#40]
We can create a changelog via Integromat of Microsoft Flow to record a row in a spreadsheet every time a survey is submitted or edited via Survey123. I have set up a basic version of this and will continue to test.

**Comment by pjdohertygis** [comment]
We have taken this as far as we can - we need help with R&D. Microsoft Flow seemed really promising but we keep getting errors. 

Is anyone proficient with Microsoft Flow or Integromat that wants to prove this out? 

We are trying to create a backup of every waypoint and all changes made. Integromat may be better. https://flow.microsoft.com/en-us/connectors/shared_survey123/survey123/

**Comment by jdokemaps** [comment]
![image](https://user-images.githubusercontent.com/52461518/75358713-95247f80-5870-11ea-812e-c85524b3fccc.png)
 This is what I had running, but it failed so many times it turned itself off.

**Comment by adf102** [comment]
I can look into this. I've seen it work with Google Sheets but I haven't tried with Microsoft 365

**Comment by adf102** [comment]
Good news - I got it to update a spreadsheet using onedrive and a survey I have. I'm going to develop it a bit more but the concept is working as it should.

**Comment by nzjs** [comment]
Hi - Paul directed me to this thread. 

We use MS Flow for this with our water quality samples. 
It logs any new records in Excel Online, we use a onedrive group shared folder.

![image](https://user-images.githubusercontent.com/5310559/75382732-e9e2fb80-593f-11ea-8d7d-66c44b98b13e.png)

I think the main thing you want to look into is:
When a Survey123 response is submitted ->
Add a row into an Excel Online (Business) sheet

One requirement is you need to create the Excel Online file first, and insert a new table into it. 
From there you'll be able to select the correct file/table to use

**Comment by pjdohertygis** [comment]
We should investigate if this will also be a capability within ArcGIS Velocity.

**Comment by pjdohertygis** [comment]
Added to our Velocity card in Planner
