### ISSUE TITLE
For v8 date field for needs follow-up, assigned, completed.

### ISSUE THREAD

**Issue by jdokemaps** [pjdohertygis/WideAreaSearchTemplates#52]
Look into creating a hidden timestamp field based on the answers in the Needs-Follow-up Field. Use if,then statments. Suggestion from Pete Hanna.

**Comment by pjdohertygis** [comment]
This might be good if it can be automated.

**Comment by pjdohertygis** [comment]
@afackler can you poke around GeoNet and see what you can find on this topic RE: timestamping when a field is changed? If you don't find anything after 30 minutes of searching - let's ask the Survey123 Team.

**Comment by afackler** [comment]
Probably worth asking the S123 team. I did some research and couldn't find anything specific
