### ISSUE TITLE
Update the FEMA PDA questions to conform to the most up to date FEMA Surveys

### ISSUE THREAD

**Issue by jdokemaps** [pjdohertygis/WideAreaSearchTemplates#54]
The PDA questions currently in the SAR survey were taken from the older version of the PDA Survey. The fields, choices, and schema need to be updated in the SAR Survey to conform to what is currently being used by FEMA. 

Also see https://github.com/pjdohertygis/SARandFirstResponderSurvey/issues/64

**Comment by pjdohertygis** [comment]
We should meet with FEMA PDA Team to discuss which fields are essential. Jared should review the existing FEMA PDA Survey.

**Comment by pjdohertygis** [comment]
Implemented and streamlined.
