### ISSUE TITLE
WAS Survey: Adopt Preliminary Damage Assessment Categories for Damage?

### ISSUE THREAD

**Issue by pjdohertygis** [pjdohertygis/WideAreaSearchTemplates#64]
The damage categories currently in use are very difficult to cross-walk into the categories used by FEMA Preliminary Damage Assessment. Hurricane Laura also showed that most teams did not really understand the current categories. There was a lack of consistency between FEMA and SUSAR Teams.
![image](https://user-images.githubusercontent.com/4256979/91885422-9928c400-ec3c-11ea-8b17-cdb0eca9ff22.png)

Of course, the Joint Damage scale would be OK too if FEMA is headed in that direciton.
![image](https://user-images.githubusercontent.com/4256979/91885458-a6de4980-ec3c-11ea-8ab4-df980bd20731.png)

**Comment by pjdohertygis** [comment]
Example from Laura - it looks like SUSAR and FEMA had different opinions on Structure, damaged vs Structure, no damage
![image](https://user-images.githubusercontent.com/4256979/91885942-6c28e100-ec3d-11ea-934b-66bff5427e7c.png)

**Comment by pjdohertygis** [comment]
Here is the guidance from Iron Sights documentation on the damage categories
![image](https://user-images.githubusercontent.com/4256979/91886025-8f539080-ec3d-11ea-9398-8be60188615a.png)

**Comment by pjdohertygis** [comment]
From Dave Weber - "Thanks Paul. I have thought a lot about our US&R four structure symbols and how they initially came to be (a compromise by the original ad hoc group) since 2014. Since we now have the ability to add more, I think the best way to deal with PDA versus US&R structure hazard symbols is to change our first four definitions to accurate PDA definitions and add three structure hazard symbols (already part of our system/training) with the definitions we currently have. I have some ppt slides I use to present to the engineers that may help.  We may be wise to also add a fourth symbol defined as “searched per ROE” since PDA and / or Structure Hazard symbols may not mean the structure was actually searched per the rules of engagement. "

**Comment by pjdohertygis** [comment]
In response to Dave Weber above - this is a similar approach to what TX-TF1 is using with their statewide deployment. 

I suggest we: 

1) Remove structure no damage, structure damage, structure failed, structure destroyed from the waypoint list. 
2) Add the PDA categories - match the field names and aliases exactly as they do in the official PDA Survey123 template.

- Destroyed - The residence is a total loss, or damaged to such an extent that repair is not feasible.
- Major   -  Sustained significant structural   damage and requires extensive repairs.
- Minor   -  a wide range of damage that does not   affect the structural integrity of the residence.
- Affected -   This category includes residences with minimal damage to the exterior of the  home and nonessential basements. Residents can remain in the structure.
- No Visible Damage
- Inaccessible - cannot be reached for assessment.

3) Add a link to the PDA Pocket Guide in the Survey instructions. 
- Destroyed - The residence is a total loss, or damaged to such an extent that repair is not feasible.
- Major   -  Sustained significant structural damage and requires extensive repairs.
- Minor   -  A wide range of damage that does not affect the structural integrity of the residence.
- Affected -  This category includes residences with minimal damage to the exterior of the home and nonessential basements. Residents can remain in the structure.

- No Visible Damage
- Inaccessible   -  cannot be reached for assessment.

4) Add a link to the PDA Pocket Guide 
https://www.fema.gov/media-library-data/1588956523083-0b0420c837695fc63e6ea8169dbf80fa/Preliminary_Damage_Assessment_Pocket_Guide.pdf

5) For any of the waypoints that are related to structures - add an optional field for "Structural hazard".

Destroyed – Complete destruction of the structure (this could be auto-populated if destroyed is chosen in the PDA category)
Structure failed –   High Risk, may be subject to structural collapse
Structure damaged –   Medium Risk, structure is moderately damaged.
Structure no damage –   Low Risk, low probability of further collapse (this could be auto-populated if No Visible Damage or Affected are chosen).

By breaking this out into an optional question we can ensure it is only used by those who are trained in structural assessment and reduce the need to add multiple waypoints. Furthermore - it may be simpler to just host the ATC-20 form for structural evaluations in the future https://safety-assessment-cusec.opendata.arcgis.com/ and skip the structural hazard question altogether.

**Comment by pjdohertygis** [comment]
From Jarrett M at FEMA Recovery 

"And yes, v3.0.3 is the most current version of our Survey123 templates."

**Comment by jdokemaps** [comment]
The PDA categories have been added to v8 of the survey. 

I used the PDA categories with the exception of "Inaccessible" for that we will most likely just use Route Blocked.
I also included an "unknown" category. This can be useful to pre-load structures into the database that have not been assessed yet.

**Comment by pjdohertygis** [comment]
"I fully agree. The need for standardization in this complex environment is critical. Making the data “line up” between Federal and State partners will add meaning and reduce the need for active deconfliction. When dealing with the collection of thousands of data points nobody wants to try to deconflict or even explain why the data doesn’t match.

It will certainly be value added if we leave data that lines up with the FEMA recovery personnel and can jumpstart the PDA process by delineating areas of damage consistent with the FEMA PDA standards." - Blue IST Planning Section Chief

**Comment by pjdohertygis** [comment]
"I will pass this along to the Search group today.  I don't foresee any real objections.  'A rose by any other name is still yet a rose.' If a structure is affected, minor (damage) major (damage) and so on, will always be subjective to a certain degree.  The true hurdle is training and compliance.  It took too many years and deployments to finally get TFs to use the WAS "Iron sights "as designed and even then, often "on the job training" had to be provided.

So, with every change comes an investment.  I agree there is value in aligning our damage assessment/marking system with the RC/FEMA PDA.  It only makes sense to do it once and in a way that works for everyone involved.
" - Deputy Fire Marshal VA Beach Fire

**Comment by pjdohertygis** [comment]
Implemented.
