### ISSUE TITLE
Enhancement: Add a "vetted" or "reviewed" field (hidden)

### ISSUE THREAD

**Issue by pjdohertygis** [pjdohertygis/WideAreaSearchTemplates#7]
We are currently discussing best practices on how to allow US&R Task Forces "approve" their data before it gets shared up the chain of command. I will add more details as we get them, but here is a quick video https://arcg.is/18uTq80

**Comment by pjdohertygis** [comment]
Feedback from NZUSAR 

This was an issue that was consistently bought up during our development and building of ICMS.. 
"We want to be able to QA/Vet information at a team level before it goes up to UCC. 
Our solution is that the form defaults to a pending state on submit and that the UCC dashboard defaults to seeing only approved forms (It can see all - TAB )  
This allows teams to update and correct form data before it goes through to UCC and has decisions made against it. 
Aidan is better placed to provide more tech stuff and method, but that's it in a nutshell. 
Regards 
Jeff 
Area Cmdr Jeff Maunder
(GradDipEmergMgmt, GradDipExecLdrshp, GradCertApplMgmt, G.I.Fire.E)
Area Manager Central Lakes Area
NZ USAR / DART Task-force 1 (NZL1)
Rotorua Fire Station 19 Biak street, Rotorua, 3015

**Comment by pjdohertygis** [comment]
Feedback from Jason W MO-TF1 
Web based app would be the minimum and assumes decent internet.  Advanced option would be ArcGIS Pro and the ability to download- edit- sync workflow and allow for batch calculations of fields that would be needed for those 2-3K+ SAR point days.

**Comment by pjdohertygis** [comment]
Here is a screenshot of the prototype currently used for the IAFC SAR Survey - search for ff000548c207428eb13c340289eb7d22 in AGOL (requires nmas or fema login)
![image](https://user-images.githubusercontent.com/4256979/64457078-8ec5ff80-d0a6-11e9-9ca8-091749a134ab.png)

**Comment by jdokemaps** [comment]
Defaults to "Not Reviewed", manually they can change to "Approved", "Needs Edit", "**Needs Deletion**". The addition of Needs Deletion would allow them to make points that were added in error. An additional attribute wording "Delete - No Longer Needed" and "Delete - Editing Mistake".

**Comment by pjdohertygis** [comment]
Question: If you publish as a hidden field type - does it publish the domains with labels? @tedrick

**Comment by tedrick** [comment]
Hidden field - no, the hidden field is a plain text question - a list in the form cannot be associated with it directly.  Either:
1. Publish initially as a select_one and then change to hidden and republish (may be supportable with your workflow given that the form includes a QR code generated after initial publishing)
2. Add the domain manually or via a script after publishing.  See [ArcGIS Online doc](https://doc.arcgis.com/en/arcgis-online/manage-data/define-attribute-lists-and-ranges.htm) (manual) and https://support.esri.com/en/technical-article/000014561 (for the REST editing needed to script it).

**Comment by pjdohertygis** [comment]
Let's go with 1. above - publish as select_one and then hide it during the republish process with the QR Code. Thanks James!

**Comment by jdokemaps** [comment]
Created a select_one field that will need to be changed to hidden during second publishing:
![image](https://user-images.githubusercontent.com/52461518/70270498-d0c41780-1761-11ea-9ade-1bff18289e0c.png)

**Comment by pjdohertygis** [comment]
Feedback from Damian CATF8 

"1. A Delay Function: a delay function to upload the survey to Dashboards in the Intel Manager. If a delay function was created, it would allow the TIS/SITL an opportunity to clean and validate the intel before it is pushed out as information. Some data collection intel may be sensitive and not sharable until approved by the local AHJ, i.e. victim data."

**Comment by pjdohertygis** [comment]
Looking for feedback on this approach. It seems like "vetting" of data coming from Survey123/QuickCapture is of growing concern and want to pitch some options. Anyone see any red flags here? A better alternative? We can discuss on the next call or just send an email or Slack
https://youtu.be/_SAhRaDMZD0?hd=1&fbclid=IwAR1rhujmwGQkkR_WOQNsl9iE7FV5K7pXboYUmf7cxoLEKpgDN5pFy7Wr1Ew

**Comment by pjdohertygis** [comment]
Ok so we are back to working on this enhancement after the Kentucky Tornado Deployment. 

"Yesterday, a "rescue" waypoint slipped through the cracks without review. 

I don't want to start filtering data from dashboards because end users won't understand it and it will cause confusion. 

HOWEVER, what if all human interaction data had a "sticker" that said Not Yet Reviewed or Not Yet Confirmed??? Then we had an indicator on the Dashboard for "Human Interactions Not Yet Reviewed". 

Would this provide a good balance of letting people know there is important, but unconfirmed data in the system? 

Adam can you prototype on the Sandbox and we can review?"

---ENTERED INTO PLANNER

**Comment by pjdohertygis** [comment]
Summary of work to date: 
- There is a field "Approval Status"
- Within this field there is a domain for "Not Yet Approved"
- In QuickCapture and Survey123 - any human interaction will default to "Not Yet Approved"
- In both Tactical and Strategic Dashboard, we added a filter for Approval Status so you both a Task Force and IST can see what still needs to be reviewed. 
- Situation Reports should not be completed until the number of waypoints with "Not Yet Approved" = 0 


![image](https://user-images.githubusercontent.com/4256979/148590137-6f9305e9-268a-47a7-9de7-f0988f1b92be.png)
![image](https://user-images.githubusercontent.com/4256979/148590315-5e45eb08-1f65-438d-9f3f-3f57b36d8a48.png)

**Comment by grover556** [comment]
I'm not sure we need to automatically mark Assist, SIP, etc as not approved. The original intent with that field was to only flag Victim/HR detect/confirm/remove and Rescue as needing a secondary confirmation.

**Comment by pjdohertygis** [comment]
> I'm not sure we need to automatically mark Assist, SIP, etc as not approved. The original intent with that field was to only flag Victim/HR detect/confirm/remove and Rescue as needing a secondary confirmation.

@grover556 - Adam @afackler will work on pairing it down next week. Thanks for the reminder.

**Comment by afackler** [comment]
I changed and tested the logic this morning, should be good to go now

**Comment by afackler** [comment]
These waypoints have a default of 'Not Yet Reviewed" and would be filtered in the dashboards as Needs Review:
- Rescued
- Victim Detected
- Victim Confirmed
- Human Remains Detected
- Human Remains Confirmed
- Human Remains Removed

Every other waypoint created in **QC or S123** defaults to "No Approval Required". Any point created in the **Intel Manager** will default to Not Yet Approved. More waypoints can be included in this list if needed now that I got the S123 logic down.

**Comment by afackler** [comment]
Met with Jack Hewitt from Esri on 2/10/22 and he showed me a method of adding a "sticker" onto the waypoint list using a combination of Arcade and HTML. He sent me the HTML and arcade logic and I will implement them into the sandbox. We can use any SVG right now and I asked him to look into including other images besides SVGs in case we want that capability later down the road. Below is a screenshot of the current result.
![image](https://user-images.githubusercontent.com/55416740/153642984-43fa4914-5377-4cf3-820a-88ece0218599.png)
