### ISSUE TITLE
New Survey123: Rapid Structure Triage 1/2

### ISSUE THREAD

**Issue by pjdohertygis** [pjdohertygis/WideAreaSearchTemplates#76]
Our existing survey is suitable for Wide Area Search, but does not contain appropriate questions for triaging structures after a large earthquake.... 

I am going to work with Jonathan on testing this form: https://arcg.is/PSyu9

This is based on the RST-1/2 form found here: http://disasterengineer.org/Library/tabid/57/Default.aspx
![image](https://user-images.githubusercontent.com/4256979/98998876-d3e48d80-2504-11eb-954d-34664d1c8856.png)

**Comment by pjdohertygis** [comment]
See for ideas on symbology https://github.com/pjdohertygis/SARandFirstResponderSurvey/issues/69

**Comment by grover556** [comment]
One of our structures guys came up with [this RST beta form](https://fema.maps.arcgis.com/home/item.html?id=4ddd3ceb7d2240afbb2c387b0d65a345) a few months back. Not sure if the polygon is the appropriate geometry, especially in a disconnected environment, but I think the Survey came out pretty well.

**Comment by pjdohertygis** [comment]
@grover556 I agree, well done and no I wouldn't use polygons for this. 

This project has grown legs so built an entirely new repository over here: https://github.com/pjdohertygis/StSTemplates

Closing.
