### ISSUE TITLE
WAS Survey - Add new waypoint: "Searched"

### ISSUE THREAD

**Issue by pjdohertygis** [pjdohertygis/WideAreaSearchTemplates#77]
From Dave Weber: We may be wise to also add a fourth symbol defined as “searched per ROE” since PDA and / or Structure Hazard symbols may not mean the structure was actually searched per the rules of engagement. "

This makes sense and has come up multiple times, how do we know if a structure (or vehicle) has been searched and no one has been found there. 

Let's ask the working group what they think. 

What would the symbol look like?

**Comment by jdokemaps** [comment]
I propose this as a symbol. The idea is that you are closing out the X on a FEMA Search Assessment Marking and it is in a circle that is representative of incident data.

![image](https://user-images.githubusercontent.com/52461518/99552046-ce120080-2979-11eb-8475-b3df83011ff9.png)

and this is what it looks like on a web map:

![image](https://user-images.githubusercontent.com/52461518/99552382-2f39d400-297a-11eb-9f66-500d89488c0a.png)

This symbol can also be used for searched cars, outbuildings, etc which don't require a damage assessment marking.

**Comment by pjdohertygis** [comment]
So we can identify what type of search it is I suggest the "Search Type" field be used as the follow-up question for this in QuickCapture and Survey123 as per Katie Breland feedback. That could then be used as a "halo" and easy access through the pop-up.

**Comment by pjdohertygis** [comment]
*IMPORTANT* @jdokemaps Never use the work "Cleared" in SAR work.  This leaves you open for lawsuits if you happen to miss someone.  Searched  works since it means you looked but it implies you looked to the best of your ability based on the current conditions

**Comment by jdokemaps** [comment]
I named this icon "Searched Per Rules of Engagement". Let me know if we need to change this.

**Comment by pjdohertygis** [comment]
Would it be wise to provide an option for "what was searched"? Vehicle vs debris vs structure? Just wondering if that would help with tallying things like vehicles? Then we can get away from adding a vehicle waypoint. Or will a comment on its own suffice?

**Comment by pjdohertygis** [comment]
This has been raised as potentially redundant with Targeted Search. Could we just use Waypoint: Targeted Search - Follow-up: Completed?

**Comment by pjdohertygis** [comment]
Here is an example where targeted search was used for "Needs Follow-up" 

![image](https://user-images.githubusercontent.com/4256979/103417289-1cf5ad00-4b58-11eb-8d77-81c31af30848.png)


Should they just have used the same waypoints and changed to completed, typed findings in comments OR is this why we need a "searched per ROE" waypoint?

**Comment by pjdohertygis** [comment]
Implemented

**Comment by pjdohertygis** [comment]
For review: 

"for the waypoint "Searched" - there is no option to search a body of water. Some ideas were adding "Flooded area - specify" and "Body of Water - specify," in which user would Specify the flooded area or body of water in Comments. For example, maybe the area being searched is a field that is flooded - so the user would select Flooded Area - specify" and write "field" and any identifying information. Also, body of water could be "lake," "river," "stream," etc. - and it would be specified in the Comments."

Let's get more information (MD-TF1?)
