### ISSUE TITLE
WAS Survey: Multiple line comments 

### ISSUE THREAD

**Issue by pjdohertygis** [pjdohertygis/WideAreaSearchTemplates#81]
From Dave Weber: In the survey, the waypoint comment and structure comment field in one line. A multiple line or the ability to return to the next line would help for editing longer text strings. @jdokemaps I believe this is possible using multiline appearance? https://doc.arcgis.com/en/survey123/desktop/create-surveys/xlsformsappearance.htm

**Comment by jdokemaps** [comment]
Created a multi-line comments field with three lines.
