### ISSUE TITLE
QuickCapture: Edit Tracks

### ISSUE THREAD

**Issue by pjdohertygis** [pjdohertygis/WideAreaSearchTemplates#84]
As more people begin using QuickCapture, we are seeing more and more "bounce" errors. 

We have provided the following guidance:

- **Location Settings:** Allow QuickCapture/Survey123 to access your location "while in use" when you install it. If you think you made a mistake or want to double-check, you can still enable apps to access your location by following these instructions: iOs: https://support.apple.com/en-us/HT203033 Android: https://support.google.com/accounts/answer/6179507?hl=en
- **WiFi Settings:** Disconnect from WiFi before leaving the building. Sometimes the device will struggle to use cell and GPS for location when it thinks it is getting a better location from WiFi. 
- **Airplane Mode:** Use airplane mode when working in a low connectivity environment. This will switch to an onboard GPS receiver and work better than trying to derive location from cell towers. It will also preserve battery life. 
- **SAR Intel Manager:** You can work with your tech info specialist or GIS Support to use the SAR Intel Manager to edit data once it has already been submitted.

HOWEVER - we are still seeing many unexplained bounce issues which makes for a very messy track and poor documentation of what has been covered. I know the QuickCapture team is working on this but is there anything else that can be done.

1) Could there be a mathematically way for the app to delete/cull questionable points based on distance and speed?
2) Could you provide the user an opportunity to delete any stray points before they submit?

**Comment by pjdohertygis** [comment]
We have incorporated guidance into the training and QuickCapture Team is working on a fix for "stray" points.

**Comment by IsmaelInRedlands** [comment]
@pjdohertygis 
While this will not resolve all stray points, please use the required accuracy project setting. This will eliminate any GPS point from the track that does not match a particular accuracy.

![image](https://user-images.githubusercontent.com/5918689/139710351-3f4b1a4b-4d2b-4725-95f4-01583779429a.png)

**Comment by pjdohertygis** [comment]
Not implemented - but we will work on training them on how to make edits in the Intel Manager.
