### ISSUE TITLE
WAS Survey: Alternative to "Paste answers from favorite"

### ISSUE THREAD

**Issue by grover556** [pjdohertygis/WideAreaSearchTemplates#86]
Consider using cached answers for Event Details part of form: Team, Squad, Name, Search Type. Favorite answers require two extra gestures per survey to populate these fields, where cached answers wouldn't require any extra work after the first survey.

**Comment by pjdohertygis** [comment]
@IsmaelInRedlands I believe cached answers are only available when using the web designer currently, correct? 

@grover556 HOWEVER, I think the Survey123 Team is working on a cached answer approach for Surveys built in Connect.
