### ISSUE TITLE
WAS Survey: Remove Operational Period

### ISSUE THREAD

**Issue by grover556** [pjdohertygis/WideAreaSearchTemplates#87]
The Operational Period field in the Event Details is redundant because it can be deduced from the Survey date/time. Even when telling team members not not populate the field, many still do, and some have the incorrect operational period anyways.

**Comment by pjdohertygis** [comment]
I raised this earlier as well. We should keep in the data model for for compatibility with Iron Sights but not expect the end user to fill this out. https://github.com/pjdohertygis/WideAreaSearchTemplates/issues/51

**Comment by jdokemaps** [comment]
Done. It is hidden in the form.
