### ISSUE TITLE
WAS QuickCapture: Once you click to add something, you cannot go back

### ISSUE THREAD

**Issue by pjdohertygis** [pjdohertygis/WideAreaSearchTemplates#89]
Once you click to add something on "Human Int. No Follow Up Needed", there is no way to ex out of it without filling in the info. For example, if I select the button for "rescued" but meant to click "evacuated", it doesn't give me an option to go back". -  TX-TF1 Tech Info Specialist.

@IsmaelInRedlands - is this something under consideration? A "back" button. Test: https://arcg.is/ObCuq

In the meantime, we will remind them of the "trash can" icon.

**Comment by IsmaelInRedlands** [comment]
The 'delete last entry' button appears automatically at the bottom of the app every time you capture a feature. 
You can configure for how long the 'delete last entry' button appears. By default it goes away after 6 seconds, but you can make it last longer if you like. You can also control if you want to show an option to edit the location of the feature or not.

**Comment by pjdohertygis** [comment]
@IsmaelInRedlands - I'll work with them on training to use the delete last entry button ("trash can") and extend the time using the json (I found it pretty easily for non-coder). I'll start with 30 seconds, do some testing, and see if this works for them. 
![image](https://user-images.githubusercontent.com/4256979/100788472-1c47ea80-33e3-11eb-9122-4a98b55abd46.png)

**Comment by pjdohertygis** [comment]
Closing this since it is not under consideration for the product - just train them to use the "trash can"
