### ISSUE TITLE
WAS QuickCapture: The blinking button for starting a new line / track, not intuitive.

### ISSUE THREAD

**Issue by pjdohertygis** [pjdohertygis/WideAreaSearchTemplates#90]
"If you click "Hasty/Rapid" first it just flashes and doesn't do anything. But if you click around and then click it again, the pop-up comes up." TX-TF1 TIS

@IsmaelInRedlands have you headed this feedback elsewhere? Anything we or Esri can do to make it more obvious?

**Comment by IsmaelInRedlands** [comment]
I am not sure I understand.
When the button flashes, it may look like it is not doing anything, but it is actually tracking you and creating a line as you move.
When you tap again to stop the flashing, then the app stops the line. If your button is configured with a [button user input](https://community.esri.com/t5/arcgis-quickcapture-blog/understanding-user-inputs-in-arcgis-quickcapture/ba-p/892208) then a dialog will appear when you stop the button so you can enter some additional information about the feature you just created.

**Comment by pjdohertygis** [comment]
@IsmaelInRedlands - I think this is more of a training issue and was surprised that two different new users did not realize how this works. I'll do some more testing with new / naive users to see how long it takes for them to figure it out. I can't really think of a way to make it more obvious myself.
