### ISSUE TITLE
WAS QuickCapture: Add the ability to add "instructions" somewhere within the app. 

### ISSUE THREAD

**Issue by pjdohertygis** [pjdohertygis/WideAreaSearchTemplates#91]
"Tracks - ‘click button’ description should be at top of buttons and not in the title." - TX-TF1 Search Team Manager. Test: https://arcg.is/ObCuq

@IsmaelInRedlands is there a way to add some additional instructions within the app interface? For instance, I wanted to let them know that they should click a button to start tracking, and then again to stop. Maybe in the short-term we need to use an app launcher button to link them out to a user guide or training videos?

**Comment by IsmaelInRedlands** [comment]
It is not possible to add buttons with notes at this moment.
Adding a video for training looks like a good idea. 
That way you can keep the UX clean rather than having help text all over the place.

**Comment by pjdohertygis** [comment]
@IsmaelInRedlands We are going to try both and see what works best. The challenge is always balancing "generic" user interface instructions with project specific details. Give this a try and let us know what you think! https://arcg.is/ObCuq


![image](https://user-images.githubusercontent.com/4256979/100911051-bae45200-349c-11eb-8065-12e56e4d1785.png)

**Comment by pjdohertygis** [comment]
This quick reference guide seems to be working well - closing.
