### ISSUE TITLE
WAS QuickCapture: Buttons User Input designated as text, showing up as numeric?

### ISSUE THREAD

**Issue by pjdohertygis** [pjdohertygis/WideAreaSearchTemplates#92]
"Damage Survey - input field defaults to numbers with no way to change to text." TX-TF1 Search Team Manager

@IsmaelInRedlands - I am attempting to track this down. I am not able to replicate this on my end, but wondering if it is some Android keyboard default? https://arcg.is/ObCuq

**Comment by IsmaelInRedlands** [comment]
Yes, this could be an issue with some Android device.
If the keyboard shown is numeric, then the user will not be able to type text.
Not a known issue so far. Do you know what device the user is using?

**Comment by pjdohertygis** [comment]
I'll check with TX-TF1 to find out what device they are using.

**Comment by pjdohertygis** [comment]
@IsmaelInRedlands I have not seen this come up again, is it fixed already?

**Comment by pjdohertygis** [comment]
@IsmaelInRedlands @xiao8579 can you please test this on the Sonim device?

**Comment by xiao8579** [comment]
Hi @pjdohertygis This is fixed on 1.10 already. I tested again with 1.12 on the Sonim, also verified the fix.

**Comment by pjdohertygis** [comment]
Thank you @xiao8579 - closing issue
