### ISSUE TITLE
WAS QuickCapture: Add coordinates to the interface

### ISSUE THREAD

**Issue by pjdohertygis** [pjdohertygis/WideAreaSearchTemplates#94]
"Coordinates - no way to see coordinates / location." TX-TF1 Search Team Manager

We have enabled this in Survey123 and presumably will be a feature in FieldMaps - but @IsmaelInRedlands it would be nice if the author could designate up to two coordinate notations to show up somewhere in the app or map? Would this drain battery life?

**Comment by IsmaelInRedlands** [comment]
Do you want to see the coordinates of your location or the coordinates of a record you have previously captured? Both?
Or do you want a button that reports your current USNG/Coordinates?

**Comment by pjdohertygis** [comment]
I will ask a few stakeholders what they think they need. We are already stamping the data collected with USNG via the device variable (which is awesome!) but this won't be visible to the QuickCapture user. 

Overall, I think being able to see your current location coordinates would be useful for reference and communication over radio "I am awaiting pick up at 11S MT 8205 6732", etc.

**Comment by pjdohertygis** [comment]
@IsmaelInRedlands - from Katie Breland on TX-TF1

"If possible it would be nice to see the USNG Coordinates of the waypoints that have been dropped and a way to see your actual USNG Coordinates of where the user is personally standing as well.  As Paul stated on the github it makes it easier to call in your location if you have the coordinates in front of you.

If not, then they can always swap to another app.

Katie"

Katie Breland | Training Manager
TEEX | Texas A&M Engineering Extension Service

**Comment by pjdohertygis** [comment]
This is expected in v1.11

**Comment by pjdohertygis** [comment]
Implemented in v1.11 but need to append the QuickCapture video. 

1) Click on GPS button at bottom 
2) Click on View Status
