### ISSUE TITLE
WAS QuickCapture: Map Interface

### ISSUE THREAD

**Issue by pjdohertygis** [pjdohertygis/WideAreaSearchTemplates#96]
"Map - allow selection of various backgrounds (road, aerial, etc.).  Map - provide scale and north arrow." TX-TF1 Search Team Manager 

I will direct them to Field Maps for this functionality, but are these things in the roadmap for QuickCapture @IsmaelInRedlands ?

**Comment by IsmaelInRedlands** [comment]
Not in the road map. We will need to understand the intended use of these features before considering.

**Comment by pjdohertygis** [comment]
Ok understood. @IsmaelInRedlands  I think we can work with the user to show how Explorer/FieldMaps can provide basemap functionality. I am not sure scale and north arrow are definite need, I'll see what else I can find out. Closing this issue for now.
