### ISSUE TITLE
WAS Survey: Remove Follow-up Form Symbol

### ISSUE THREAD

**Issue by pjdohertygis** [pjdohertygis/WideAreaSearchTemplates#97]
"Finally, I think the follow-up symbol can be retired since we effectively have no tie to the old iron sights symbol set any more.  These issues should probably get search working group weigh in if possible." - Dave Weber

**Comment by pjdohertygis** [comment]
I agree we can remove this waypoint since we now have the ability to flag waypoints for Follow-up. 

HOWEVER - I think we should still request they keep Follow-up Forms with them since we cannot enter PII and other sensitive (albeit) tactical information into the system (it violates the privacy policy we are acting under and could jeopardize the system). 

So imagine a scenario where you Rescue two victims (mark rescue, 2 people). But there is one victim still trapped (mark as victim confirmed, 1, needs follow-up). If you wanted to record the victims name, age, medical conditions - the squad in the field, the PTM, and others have a "need to know" - but that information CANNOT be entered into the system. If however, you record the USNG of where this occurred you could can write this on the Follow-up Form, share via secure comms, etc. 

This use of Follow-up Form (paper) and PII is really important and should be documented.

**Comment by jdokemaps** [comment]
Follow-up waypoint deleted in the survey.
