### ISSUE TITLE
QuickCapture: Be able to designate some questions as requiring map input vs GPS

### ISSUE THREAD

**Issue by pjdohertygis** [pjdohertygis/WideAreaSearchTemplates#99]
**Real-world Problem:** While GPS accuracy is good enough for several of the waypoint types - damage assessments really need to placed on the actual building they are observing. While we are trying to train them to click on the pencil and edit the location - they sometimes forget or miss the training. 

**Proposed Solution:** Would it be possible to "prompt" them to check the map, by automatically opening the map after entry for some specific questions? The author would it configure it for some questions but not others. It would be a way to say - "hey, for this entry, check your location, it is important!". 

@IsmaelInRedlands let us know if it would be helpful to get this on the ArcGIS Ideas website, unless this is already under consideration.

**Comment by pjdohertygis** [comment]
Here is an example of what happened with Survey123 this year because no one was there to train them to drag the pin to the building - all the points are in the middle of the street :( 
![image](https://user-images.githubusercontent.com/4256979/102228906-3c82a980-3eb9-11eb-9101-b1af2c494fd0.png)

**Comment by IsmaelInRedlands** [comment]
Hi. 
The function **pulldata("@geopoint",${location},"positionSourceType")** will return 1 if the location was set using a GPS, and 2 if set manually by the user dragging the map. 3 means an external GPS was used.
You could use this information to make a warning note visible or alternatively to create a constraint.

Here is an example:  [PositionSourceExample.xlsx](https://github.com/pjdohertygis/WideAreaSearchTemplates/files/5697164/PositionSourceExample.xlsx)

**Comment by IsmaelInRedlands** [comment]
Ok. Now that I read the whole issue here I understand. This issue is about QuickCapture, not Survey123.  This is not in our radar and has not come up before. Yes, this is a good candidate for a GeoNet Idea.

**Comment by pjdohertygis** [comment]
Ok added as an Idea here: https://community.esri.com/t5/arcgis-quickcapture-ideas/quickcapture-prompt-user-to-use-map-to-improve-accuracy-aka-drag/idi-p/1012095

**Comment by pjdohertygis** [comment]
@IsmaelInRedlands mentioned that this is a reasonable enhancement. Allow the author to configure which questions require "map validation".

**Comment by pjdohertygis** [comment]
"Our next goal is to provide an option to QuickCapture authors to make the map be automatically shown when a button is pushed. The purpose of showing the map is for the end user to validate, update and/or confirm the location of the observation added using the map. We plan to have an option to define a custom hint so users are clear on what they are supposed to do with the map. For example, you could set the hint to: ‘Make sure the pushpin is on top of the building’. This design is based on your feedback. Tentative delivery date for this in Beta: before end of January" - from QuickCapture Team on 12/17.

**Comment by IsmaelInRedlands** [comment]
Delivery date change early March 2022.

**Comment by pjdohertygis** [comment]
Adding comment from another thread here. 

"For the QuickCapture v1.13 bullet point, do we have the ability to conditionally require map input based on active search type? For example, we've begun the discussion about requiring map input on certain types of searches and/or waypoints. Lets see if we can require map input for Targeted and Secondary, not for Hasty or Recon, and maybe for Primary. I can see the flip side of having to move a point that doesn't need moved when you're standing where you want to collect." @grover556 (can't tag you for some reason Collin).

**Comment by pjdohertygis** [comment]
@grover556

I'll let Esri speak to the ability to use one button (tracklogs) to control the behavior of other buttons (waypoints).... 

But first, it would be good for you to see the design of what they propose. It looks like it will be minimally obtrusive and won't require you move the pin, it will just prompt you to look at the map and see your location and the pin location, with a basemap to guide you. So it may not add a burden to the end user at all, they may be able to just skip it. 

But there is also a non-technology discussion here. For damage assessment waypoints, I'd argue we need to revise the ROE and the data dictionary https://napsg.maps.arcgis.com/home/item.html?id=bd05cb0919744c8fb02e34c694d39971

**1) Recon** - don't add damage assessment waypoints,  you might add one or two for a general idea of damage at a specific location (e.g., a hospital or a bridge?), but why add to every structure if you aren't stopping to search it? 
**2) Hasty** - don't add damage assessment,  you might add one or two for a general idea of damage at a location where you stopped to do a rescue, but why add to every structure if you aren't stopping to search it? 
**3) Primary** - If you are searching / knocking doors at each structure, it only take a second to validate the location of the point, especially if you are standing at the structure. Why would you map it in the middle of the street, it means nothing and helps no one? It actually ends up being really confusing when there are more or less points on a street than there are structures, especially when the tracklogs are also in the middle of the street. 
4) Secondary - If you are physically searching a structure, you should already be standing on top or in it - take a second to confirm the location. 
5) Targeted - depends on the situation but could be similar to Primary.

**Comment by pjdohertygis** [comment]
Currently testing on v1.13.03!

**Comment by pjdohertygis** [comment]
This enhancement is working really well! We first implemented for damage assessment waypoints only, but today I had a few task force members (CATF8) suggest we also prompt with a map for any human interactions as well. @jdokemaps @afackler - I have implemented "map input" for human interactions in the Sandbox and FEMA for now. Let's see how they respond to this in the next exercise.

**Comment by pjdohertygis** [comment]
Implemented in v1.13! Thank you @IsmaelInRedlands and team!
